/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexico.node;

import lexico.analysis.*;

@SuppressWarnings("nls")
public final class TIdClasse extends Token
{
    public TIdClasse(String text)
    {
        setText(text);
    }

    public TIdClasse(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TIdClasse(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIdClasse(this);
    }
}
