/* This file was generated by SableCC (http://www.sablecc.org/). */

package fatorial.node;

import fatorial.analysis.*;

@SuppressWarnings("nls")
public final class TPalavra extends Token
{
    public TPalavra(String text)
    {
        setText(text);
    }

    public TPalavra(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPalavra(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPalavra(this);
    }
}
