/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AAlteravelModificador extends PModificador
{
    private TAlterable _alterable_;

    public AAlteravelModificador()
    {
        // Constructor
    }

    public AAlteravelModificador(
        @SuppressWarnings("hiding") TAlterable _alterable_)
    {
        // Constructor
        setAlterable(_alterable_);

    }

    @Override
    public Object clone()
    {
        return new AAlteravelModificador(
            cloneNode(this._alterable_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAlteravelModificador(this);
    }

    public TAlterable getAlterable()
    {
        return this._alterable_;
    }

    public void setAlterable(TAlterable node)
    {
        if(this._alterable_ != null)
        {
            this._alterable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._alterable_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._alterable_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._alterable_ == child)
        {
            this._alterable_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._alterable_ == oldChild)
        {
            setAlterable((TAlterable) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
