/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ABaseListaMaisExp extends PListaMaisExp
{

    public ABaseListaMaisExp()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new ABaseListaMaisExp();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABaseListaMaisExp(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
