/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ABaseListaPrefixoAcesso extends PListaPrefixoAcesso
{
    private PPrefixoAcesso _prefixoAcesso_;

    public ABaseListaPrefixoAcesso()
    {
        // Constructor
    }

    public ABaseListaPrefixoAcesso(
        @SuppressWarnings("hiding") PPrefixoAcesso _prefixoAcesso_)
    {
        // Constructor
        setPrefixoAcesso(_prefixoAcesso_);

    }

    @Override
    public Object clone()
    {
        return new ABaseListaPrefixoAcesso(
            cloneNode(this._prefixoAcesso_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABaseListaPrefixoAcesso(this);
    }

    public PPrefixoAcesso getPrefixoAcesso()
    {
        return this._prefixoAcesso_;
    }

    public void setPrefixoAcesso(PPrefixoAcesso node)
    {
        if(this._prefixoAcesso_ != null)
        {
            this._prefixoAcesso_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prefixoAcesso_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._prefixoAcesso_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._prefixoAcesso_ == child)
        {
            this._prefixoAcesso_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._prefixoAcesso_ == oldChild)
        {
            setPrefixoAcesso((PPrefixoAcesso) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
