/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ABaseListaDefinicaoCorpo extends PListaDefinicaoCorpo
{
    private PDeclaracaoClasse _declaracaoClasse_;

    public ABaseListaDefinicaoCorpo()
    {
        // Constructor
    }

    public ABaseListaDefinicaoCorpo(
        @SuppressWarnings("hiding") PDeclaracaoClasse _declaracaoClasse_)
    {
        // Constructor
        setDeclaracaoClasse(_declaracaoClasse_);

    }

    @Override
    public Object clone()
    {
        return new ABaseListaDefinicaoCorpo(
            cloneNode(this._declaracaoClasse_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABaseListaDefinicaoCorpo(this);
    }

    public PDeclaracaoClasse getDeclaracaoClasse()
    {
        return this._declaracaoClasse_;
    }

    public void setDeclaracaoClasse(PDeclaracaoClasse node)
    {
        if(this._declaracaoClasse_ != null)
        {
            this._declaracaoClasse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracaoClasse_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declaracaoClasse_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declaracaoClasse_ == child)
        {
            this._declaracaoClasse_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declaracaoClasse_ == oldChild)
        {
            setDeclaracaoClasse((PDeclaracaoClasse) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
