/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ABlocoComandos extends PBlocoComandos
{
    private TStart _start_;
    private PListaComando _listaComando_;
    private TFinish _finish_;

    public ABlocoComandos()
    {
        // Constructor
    }

    public ABlocoComandos(
        @SuppressWarnings("hiding") TStart _start_,
        @SuppressWarnings("hiding") PListaComando _listaComando_,
        @SuppressWarnings("hiding") TFinish _finish_)
    {
        // Constructor
        setStart(_start_);

        setListaComando(_listaComando_);

        setFinish(_finish_);

    }

    @Override
    public Object clone()
    {
        return new ABlocoComandos(
            cloneNode(this._start_),
            cloneNode(this._listaComando_),
            cloneNode(this._finish_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlocoComandos(this);
    }

    public TStart getStart()
    {
        return this._start_;
    }

    public void setStart(TStart node)
    {
        if(this._start_ != null)
        {
            this._start_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._start_ = node;
    }

    public PListaComando getListaComando()
    {
        return this._listaComando_;
    }

    public void setListaComando(PListaComando node)
    {
        if(this._listaComando_ != null)
        {
            this._listaComando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaComando_ = node;
    }

    public TFinish getFinish()
    {
        return this._finish_;
    }

    public void setFinish(TFinish node)
    {
        if(this._finish_ != null)
        {
            this._finish_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._finish_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._start_)
            + toString(this._listaComando_)
            + toString(this._finish_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._start_ == child)
        {
            this._start_ = null;
            return;
        }

        if(this._listaComando_ == child)
        {
            this._listaComando_ = null;
            return;
        }

        if(this._finish_ == child)
        {
            this._finish_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._start_ == oldChild)
        {
            setStart((TStart) newChild);
            return;
        }

        if(this._listaComando_ == oldChild)
        {
            setListaComando((PListaComando) newChild);
            return;
        }

        if(this._finish_ == oldChild)
        {
            setFinish((TFinish) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
