/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ABlocoStart extends PBlocoStart
{
    private TStart _start_;
    private PBlocoComandos _blocoComandos_;

    public ABlocoStart()
    {
        // Constructor
    }

    public ABlocoStart(
        @SuppressWarnings("hiding") TStart _start_,
        @SuppressWarnings("hiding") PBlocoComandos _blocoComandos_)
    {
        // Constructor
        setStart(_start_);

        setBlocoComandos(_blocoComandos_);

    }

    @Override
    public Object clone()
    {
        return new ABlocoStart(
            cloneNode(this._start_),
            cloneNode(this._blocoComandos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlocoStart(this);
    }

    public TStart getStart()
    {
        return this._start_;
    }

    public void setStart(TStart node)
    {
        if(this._start_ != null)
        {
            this._start_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._start_ = node;
    }

    public PBlocoComandos getBlocoComandos()
    {
        return this._blocoComandos_;
    }

    public void setBlocoComandos(PBlocoComandos node)
    {
        if(this._blocoComandos_ != null)
        {
            this._blocoComandos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._blocoComandos_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._start_)
            + toString(this._blocoComandos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._start_ == child)
        {
            this._start_ = null;
            return;
        }

        if(this._blocoComandos_ == child)
        {
            this._blocoComandos_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._start_ == oldChild)
        {
            setStart((TStart) newChild);
            return;
        }

        if(this._blocoComandos_ == oldChild)
        {
            setBlocoComandos((PBlocoComandos) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
