/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ABlocoExp extends PBlocoExp
{
    private TStart _start_;
    private PListaDecLocal _listaDecLocal_;
    private PListaComando _listaComando_;
    private PExpressao _expressao_;
    private TFinish _finish_;

    public ABlocoExp()
    {
        // Constructor
    }

    public ABlocoExp(
        @SuppressWarnings("hiding") TStart _start_,
        @SuppressWarnings("hiding") PListaDecLocal _listaDecLocal_,
        @SuppressWarnings("hiding") PListaComando _listaComando_,
        @SuppressWarnings("hiding") PExpressao _expressao_,
        @SuppressWarnings("hiding") TFinish _finish_)
    {
        // Constructor
        setStart(_start_);

        setListaDecLocal(_listaDecLocal_);

        setListaComando(_listaComando_);

        setExpressao(_expressao_);

        setFinish(_finish_);

    }

    @Override
    public Object clone()
    {
        return new ABlocoExp(
            cloneNode(this._start_),
            cloneNode(this._listaDecLocal_),
            cloneNode(this._listaComando_),
            cloneNode(this._expressao_),
            cloneNode(this._finish_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlocoExp(this);
    }

    public TStart getStart()
    {
        return this._start_;
    }

    public void setStart(TStart node)
    {
        if(this._start_ != null)
        {
            this._start_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._start_ = node;
    }

    public PListaDecLocal getListaDecLocal()
    {
        return this._listaDecLocal_;
    }

    public void setListaDecLocal(PListaDecLocal node)
    {
        if(this._listaDecLocal_ != null)
        {
            this._listaDecLocal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaDecLocal_ = node;
    }

    public PListaComando getListaComando()
    {
        return this._listaComando_;
    }

    public void setListaComando(PListaComando node)
    {
        if(this._listaComando_ != null)
        {
            this._listaComando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaComando_ = node;
    }

    public PExpressao getExpressao()
    {
        return this._expressao_;
    }

    public void setExpressao(PExpressao node)
    {
        if(this._expressao_ != null)
        {
            this._expressao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressao_ = node;
    }

    public TFinish getFinish()
    {
        return this._finish_;
    }

    public void setFinish(TFinish node)
    {
        if(this._finish_ != null)
        {
            this._finish_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._finish_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._start_)
            + toString(this._listaDecLocal_)
            + toString(this._listaComando_)
            + toString(this._expressao_)
            + toString(this._finish_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._start_ == child)
        {
            this._start_ = null;
            return;
        }

        if(this._listaDecLocal_ == child)
        {
            this._listaDecLocal_ = null;
            return;
        }

        if(this._listaComando_ == child)
        {
            this._listaComando_ = null;
            return;
        }

        if(this._expressao_ == child)
        {
            this._expressao_ = null;
            return;
        }

        if(this._finish_ == child)
        {
            this._finish_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._start_ == oldChild)
        {
            setStart((TStart) newChild);
            return;
        }

        if(this._listaDecLocal_ == oldChild)
        {
            setListaDecLocal((PListaDecLocal) newChild);
            return;
        }

        if(this._listaComando_ == oldChild)
        {
            setListaComando((PListaComando) newChild);
            return;
        }

        if(this._expressao_ == oldChild)
        {
            setExpressao((PExpressao) newChild);
            return;
        }

        if(this._finish_ == oldChild)
        {
            setFinish((TFinish) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
