/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ABlocoComponentes extends PBlocoComponentes
{
    private TColcEsq _colcEsq_;
    private PListaComponentes _listaComponentes_;
    private TColcDir _colcDir_;

    public ABlocoComponentes()
    {
        // Constructor
    }

    public ABlocoComponentes(
        @SuppressWarnings("hiding") TColcEsq _colcEsq_,
        @SuppressWarnings("hiding") PListaComponentes _listaComponentes_,
        @SuppressWarnings("hiding") TColcDir _colcDir_)
    {
        // Constructor
        setColcEsq(_colcEsq_);

        setListaComponentes(_listaComponentes_);

        setColcDir(_colcDir_);

    }

    @Override
    public Object clone()
    {
        return new ABlocoComponentes(
            cloneNode(this._colcEsq_),
            cloneNode(this._listaComponentes_),
            cloneNode(this._colcDir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlocoComponentes(this);
    }

    public TColcEsq getColcEsq()
    {
        return this._colcEsq_;
    }

    public void setColcEsq(TColcEsq node)
    {
        if(this._colcEsq_ != null)
        {
            this._colcEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colcEsq_ = node;
    }

    public PListaComponentes getListaComponentes()
    {
        return this._listaComponentes_;
    }

    public void setListaComponentes(PListaComponentes node)
    {
        if(this._listaComponentes_ != null)
        {
            this._listaComponentes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaComponentes_ = node;
    }

    public TColcDir getColcDir()
    {
        return this._colcDir_;
    }

    public void setColcDir(TColcDir node)
    {
        if(this._colcDir_ != null)
        {
            this._colcDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colcDir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._colcEsq_)
            + toString(this._listaComponentes_)
            + toString(this._colcDir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._colcEsq_ == child)
        {
            this._colcEsq_ = null;
            return;
        }

        if(this._listaComponentes_ == child)
        {
            this._listaComponentes_ = null;
            return;
        }

        if(this._colcDir_ == child)
        {
            this._colcDir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._colcEsq_ == oldChild)
        {
            setColcEsq((TColcEsq) newChild);
            return;
        }

        if(this._listaComponentes_ == oldChild)
        {
            setListaComponentes((PListaComponentes) newChild);
            return;
        }

        if(this._colcDir_ == oldChild)
        {
            setColcDir((TColcDir) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
