/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ABlocoComando extends PComando
{
    private PBlocoComandos _blocoComandos_;

    public ABlocoComando()
    {
        // Constructor
    }

    public ABlocoComando(
        @SuppressWarnings("hiding") PBlocoComandos _blocoComandos_)
    {
        // Constructor
        setBlocoComandos(_blocoComandos_);

    }

    @Override
    public Object clone()
    {
        return new ABlocoComando(
            cloneNode(this._blocoComandos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlocoComando(this);
    }

    public PBlocoComandos getBlocoComandos()
    {
        return this._blocoComandos_;
    }

    public void setBlocoComandos(PBlocoComandos node)
    {
        if(this._blocoComandos_ != null)
        {
            this._blocoComandos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._blocoComandos_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._blocoComandos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._blocoComandos_ == child)
        {
            this._blocoComandos_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._blocoComandos_ == oldChild)
        {
            setBlocoComandos((PBlocoComandos) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
