/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ABooleanoTipoPrimitivo extends PTipoPrimitivo
{
    private TAnswer _answer_;

    public ABooleanoTipoPrimitivo()
    {
        // Constructor
    }

    public ABooleanoTipoPrimitivo(
        @SuppressWarnings("hiding") TAnswer _answer_)
    {
        // Constructor
        setAnswer(_answer_);

    }

    @Override
    public Object clone()
    {
        return new ABooleanoTipoPrimitivo(
            cloneNode(this._answer_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABooleanoTipoPrimitivo(this);
    }

    public TAnswer getAnswer()
    {
        return this._answer_;
    }

    public void setAnswer(TAnswer node)
    {
        if(this._answer_ != null)
        {
            this._answer_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._answer_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._answer_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._answer_ == child)
        {
            this._answer_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._answer_ == oldChild)
        {
            setAnswer((TAnswer) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
