/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ABooleanoFFator extends PFator
{
    private TNo _no_;

    public ABooleanoFFator()
    {
        // Constructor
    }

    public ABooleanoFFator(
        @SuppressWarnings("hiding") TNo _no_)
    {
        // Constructor
        setNo(_no_);

    }

    @Override
    public Object clone()
    {
        return new ABooleanoFFator(
            cloneNode(this._no_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABooleanoFFator(this);
    }

    public TNo getNo()
    {
        return this._no_;
    }

    public void setNo(TNo node)
    {
        if(this._no_ != null)
        {
            this._no_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._no_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._no_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._no_ == child)
        {
            this._no_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._no_ == oldChild)
        {
            setNo((TNo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
