/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AChamadaExprFator extends PFator
{
    private TId _id_;
    private TColcEsq _colcEsq_;
    private PListaExp _listaExp_;
    private TColcDir _colcDir_;

    public AChamadaExprFator()
    {
        // Constructor
    }

    public AChamadaExprFator(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TColcEsq _colcEsq_,
        @SuppressWarnings("hiding") PListaExp _listaExp_,
        @SuppressWarnings("hiding") TColcDir _colcDir_)
    {
        // Constructor
        setId(_id_);

        setColcEsq(_colcEsq_);

        setListaExp(_listaExp_);

        setColcDir(_colcDir_);

    }

    @Override
    public Object clone()
    {
        return new AChamadaExprFator(
            cloneNode(this._id_),
            cloneNode(this._colcEsq_),
            cloneNode(this._listaExp_),
            cloneNode(this._colcDir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAChamadaExprFator(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TColcEsq getColcEsq()
    {
        return this._colcEsq_;
    }

    public void setColcEsq(TColcEsq node)
    {
        if(this._colcEsq_ != null)
        {
            this._colcEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colcEsq_ = node;
    }

    public PListaExp getListaExp()
    {
        return this._listaExp_;
    }

    public void setListaExp(PListaExp node)
    {
        if(this._listaExp_ != null)
        {
            this._listaExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaExp_ = node;
    }

    public TColcDir getColcDir()
    {
        return this._colcDir_;
    }

    public void setColcDir(TColcDir node)
    {
        if(this._colcDir_ != null)
        {
            this._colcDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colcDir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._colcEsq_)
            + toString(this._listaExp_)
            + toString(this._colcDir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._colcEsq_ == child)
        {
            this._colcEsq_ = null;
            return;
        }

        if(this._listaExp_ == child)
        {
            this._listaExp_ = null;
            return;
        }

        if(this._colcDir_ == child)
        {
            this._colcDir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._colcEsq_ == oldChild)
        {
            setColcEsq((TColcEsq) newChild);
            return;
        }

        if(this._listaExp_ == oldChild)
        {
            setListaExp((PListaExp) newChild);
            return;
        }

        if(this._colcDir_ == oldChild)
        {
            setColcDir((TColcDir) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
