/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AComParametrosOptParametros extends POptParametros
{
    private PParametros _parametros_;

    public AComParametrosOptParametros()
    {
        // Constructor
    }

    public AComParametrosOptParametros(
        @SuppressWarnings("hiding") PParametros _parametros_)
    {
        // Constructor
        setParametros(_parametros_);

    }

    @Override
    public Object clone()
    {
        return new AComParametrosOptParametros(
            cloneNode(this._parametros_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComParametrosOptParametros(this);
    }

    public PParametros getParametros()
    {
        return this._parametros_;
    }

    public void setParametros(PParametros node)
    {
        if(this._parametros_ != null)
        {
            this._parametros_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametros_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parametros_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parametros_ == child)
        {
            this._parametros_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parametros_ == oldChild)
        {
            setParametros((PParametros) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
