/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AComGenealogiaOptGenealogia extends POptGenealogia
{
    private PGenealogia _genealogia_;

    public AComGenealogiaOptGenealogia()
    {
        // Constructor
    }

    public AComGenealogiaOptGenealogia(
        @SuppressWarnings("hiding") PGenealogia _genealogia_)
    {
        // Constructor
        setGenealogia(_genealogia_);

    }

    @Override
    public Object clone()
    {
        return new AComGenealogiaOptGenealogia(
            cloneNode(this._genealogia_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComGenealogiaOptGenealogia(this);
    }

    public PGenealogia getGenealogia()
    {
        return this._genealogia_;
    }

    public void setGenealogia(PGenealogia node)
    {
        if(this._genealogia_ != null)
        {
            this._genealogia_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._genealogia_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._genealogia_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._genealogia_ == child)
        {
            this._genealogia_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._genealogia_ == oldChild)
        {
            setGenealogia((PGenealogia) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
