/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AComMarcadorOptMarcadorEntrada extends POptMarcadorEntrada
{
    private TMarcadorEntrada _marcadorEntrada_;

    public AComMarcadorOptMarcadorEntrada()
    {
        // Constructor
    }

    public AComMarcadorOptMarcadorEntrada(
        @SuppressWarnings("hiding") TMarcadorEntrada _marcadorEntrada_)
    {
        // Constructor
        setMarcadorEntrada(_marcadorEntrada_);

    }

    @Override
    public Object clone()
    {
        return new AComMarcadorOptMarcadorEntrada(
            cloneNode(this._marcadorEntrada_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComMarcadorOptMarcadorEntrada(this);
    }

    public TMarcadorEntrada getMarcadorEntrada()
    {
        return this._marcadorEntrada_;
    }

    public void setMarcadorEntrada(TMarcadorEntrada node)
    {
        if(this._marcadorEntrada_ != null)
        {
            this._marcadorEntrada_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._marcadorEntrada_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._marcadorEntrada_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._marcadorEntrada_ == child)
        {
            this._marcadorEntrada_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._marcadorEntrada_ == oldChild)
        {
            setMarcadorEntrada((TMarcadorEntrada) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
