/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ADecVar extends PDecVar
{
    private PTipoPrimitivo _tipoPrimitivo_;
    private TId _id_;
    private PExpressao _expressao_;

    public ADecVar()
    {
        // Constructor
    }

    public ADecVar(
        @SuppressWarnings("hiding") PTipoPrimitivo _tipoPrimitivo_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PExpressao _expressao_)
    {
        // Constructor
        setTipoPrimitivo(_tipoPrimitivo_);

        setId(_id_);

        setExpressao(_expressao_);

    }

    @Override
    public Object clone()
    {
        return new ADecVar(
            cloneNode(this._tipoPrimitivo_),
            cloneNode(this._id_),
            cloneNode(this._expressao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecVar(this);
    }

    public PTipoPrimitivo getTipoPrimitivo()
    {
        return this._tipoPrimitivo_;
    }

    public void setTipoPrimitivo(PTipoPrimitivo node)
    {
        if(this._tipoPrimitivo_ != null)
        {
            this._tipoPrimitivo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoPrimitivo_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PExpressao getExpressao()
    {
        return this._expressao_;
    }

    public void setExpressao(PExpressao node)
    {
        if(this._expressao_ != null)
        {
            this._expressao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipoPrimitivo_)
            + toString(this._id_)
            + toString(this._expressao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipoPrimitivo_ == child)
        {
            this._tipoPrimitivo_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._expressao_ == child)
        {
            this._expressao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipoPrimitivo_ == oldChild)
        {
            setTipoPrimitivo((PTipoPrimitivo) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._expressao_ == oldChild)
        {
            setExpressao((PExpressao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
