/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ADeclaracaoClasse extends PDeclaracaoClasse
{
    private TFamily _family_;
    private TIdClasse _idClasse_;
    private TStart _start_;
    private PListaComponentes _listaComponentes_;
    private TFinish _finish_;

    public ADeclaracaoClasse()
    {
        // Constructor
    }

    public ADeclaracaoClasse(
        @SuppressWarnings("hiding") TFamily _family_,
        @SuppressWarnings("hiding") TIdClasse _idClasse_,
        @SuppressWarnings("hiding") TStart _start_,
        @SuppressWarnings("hiding") PListaComponentes _listaComponentes_,
        @SuppressWarnings("hiding") TFinish _finish_)
    {
        // Constructor
        setFamily(_family_);

        setIdClasse(_idClasse_);

        setStart(_start_);

        setListaComponentes(_listaComponentes_);

        setFinish(_finish_);

    }

    @Override
    public Object clone()
    {
        return new ADeclaracaoClasse(
            cloneNode(this._family_),
            cloneNode(this._idClasse_),
            cloneNode(this._start_),
            cloneNode(this._listaComponentes_),
            cloneNode(this._finish_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclaracaoClasse(this);
    }

    public TFamily getFamily()
    {
        return this._family_;
    }

    public void setFamily(TFamily node)
    {
        if(this._family_ != null)
        {
            this._family_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._family_ = node;
    }

    public TIdClasse getIdClasse()
    {
        return this._idClasse_;
    }

    public void setIdClasse(TIdClasse node)
    {
        if(this._idClasse_ != null)
        {
            this._idClasse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._idClasse_ = node;
    }

    public TStart getStart()
    {
        return this._start_;
    }

    public void setStart(TStart node)
    {
        if(this._start_ != null)
        {
            this._start_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._start_ = node;
    }

    public PListaComponentes getListaComponentes()
    {
        return this._listaComponentes_;
    }

    public void setListaComponentes(PListaComponentes node)
    {
        if(this._listaComponentes_ != null)
        {
            this._listaComponentes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaComponentes_ = node;
    }

    public TFinish getFinish()
    {
        return this._finish_;
    }

    public void setFinish(TFinish node)
    {
        if(this._finish_ != null)
        {
            this._finish_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._finish_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._family_)
            + toString(this._idClasse_)
            + toString(this._start_)
            + toString(this._listaComponentes_)
            + toString(this._finish_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._family_ == child)
        {
            this._family_ = null;
            return;
        }

        if(this._idClasse_ == child)
        {
            this._idClasse_ = null;
            return;
        }

        if(this._start_ == child)
        {
            this._start_ = null;
            return;
        }

        if(this._listaComponentes_ == child)
        {
            this._listaComponentes_ = null;
            return;
        }

        if(this._finish_ == child)
        {
            this._finish_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._family_ == oldChild)
        {
            setFamily((TFamily) newChild);
            return;
        }

        if(this._idClasse_ == oldChild)
        {
            setIdClasse((TIdClasse) newChild);
            return;
        }

        if(this._start_ == oldChild)
        {
            setStart((TStart) newChild);
            return;
        }

        if(this._listaComponentes_ == oldChild)
        {
            setListaComponentes((PListaComponentes) newChild);
            return;
        }

        if(this._finish_ == oldChild)
        {
            setFinish((TFinish) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
