/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import java.util.*;
import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ADeclaracaoClasse extends PDeclaracaoClasse
{
    private TIdClasse _idClasse_;
    private final LinkedList<PComponentes> _componentes_ = new LinkedList<PComponentes>();

    public ADeclaracaoClasse()
    {
        // Constructor
    }

    public ADeclaracaoClasse(
        @SuppressWarnings("hiding") TIdClasse _idClasse_,
        @SuppressWarnings("hiding") List<?> _componentes_)
    {
        // Constructor
        setIdClasse(_idClasse_);

        setComponentes(_componentes_);

    }

    @Override
    public Object clone()
    {
        return new ADeclaracaoClasse(
            cloneNode(this._idClasse_),
            cloneList(this._componentes_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclaracaoClasse(this);
    }

    public TIdClasse getIdClasse()
    {
        return this._idClasse_;
    }

    public void setIdClasse(TIdClasse node)
    {
        if(this._idClasse_ != null)
        {
            this._idClasse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._idClasse_ = node;
    }

    public LinkedList<PComponentes> getComponentes()
    {
        return this._componentes_;
    }

    public void setComponentes(List<?> list)
    {
        for(PComponentes e : this._componentes_)
        {
            e.parent(null);
        }
        this._componentes_.clear();

        for(Object obj_e : list)
        {
            PComponentes e = (PComponentes) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._componentes_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._idClasse_)
            + toString(this._componentes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._idClasse_ == child)
        {
            this._idClasse_ = null;
            return;
        }

        if(this._componentes_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._idClasse_ == oldChild)
        {
            setIdClasse((TIdClasse) newChild);
            return;
        }

        for(ListIterator<PComponentes> i = this._componentes_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PComponentes) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
