/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AEExpressaoAnd extends PExpressaoAnd
{
    private PExpressaoAnd _expressaoAnd_;
    private TAnd _and_;
    private PExpressaoRelacional _expressaoRelacional_;

    public AEExpressaoAnd()
    {
        // Constructor
    }

    public AEExpressaoAnd(
        @SuppressWarnings("hiding") PExpressaoAnd _expressaoAnd_,
        @SuppressWarnings("hiding") TAnd _and_,
        @SuppressWarnings("hiding") PExpressaoRelacional _expressaoRelacional_)
    {
        // Constructor
        setExpressaoAnd(_expressaoAnd_);

        setAnd(_and_);

        setExpressaoRelacional(_expressaoRelacional_);

    }

    @Override
    public Object clone()
    {
        return new AEExpressaoAnd(
            cloneNode(this._expressaoAnd_),
            cloneNode(this._and_),
            cloneNode(this._expressaoRelacional_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEExpressaoAnd(this);
    }

    public PExpressaoAnd getExpressaoAnd()
    {
        return this._expressaoAnd_;
    }

    public void setExpressaoAnd(PExpressaoAnd node)
    {
        if(this._expressaoAnd_ != null)
        {
            this._expressaoAnd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoAnd_ = node;
    }

    public TAnd getAnd()
    {
        return this._and_;
    }

    public void setAnd(TAnd node)
    {
        if(this._and_ != null)
        {
            this._and_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._and_ = node;
    }

    public PExpressaoRelacional getExpressaoRelacional()
    {
        return this._expressaoRelacional_;
    }

    public void setExpressaoRelacional(PExpressaoRelacional node)
    {
        if(this._expressaoRelacional_ != null)
        {
            this._expressaoRelacional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoRelacional_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressaoAnd_)
            + toString(this._and_)
            + toString(this._expressaoRelacional_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressaoAnd_ == child)
        {
            this._expressaoAnd_ = null;
            return;
        }

        if(this._and_ == child)
        {
            this._and_ = null;
            return;
        }

        if(this._expressaoRelacional_ == child)
        {
            this._expressaoRelacional_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressaoAnd_ == oldChild)
        {
            setExpressaoAnd((PExpressaoAnd) newChild);
            return;
        }

        if(this._and_ == oldChild)
        {
            setAnd((TAnd) newChild);
            return;
        }

        if(this._expressaoRelacional_ == oldChild)
        {
            setExpressaoRelacional((PExpressaoRelacional) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
