/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import java.util.*;
import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AGenealogia extends PGenealogia
{
    private final LinkedList<PRelacao> _relacao_ = new LinkedList<PRelacao>();

    public AGenealogia()
    {
        // Constructor
    }

    public AGenealogia(
        @SuppressWarnings("hiding") List<?> _relacao_)
    {
        // Constructor
        setRelacao(_relacao_);

    }

    @Override
    public Object clone()
    {
        return new AGenealogia(
            cloneList(this._relacao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGenealogia(this);
    }

    public LinkedList<PRelacao> getRelacao()
    {
        return this._relacao_;
    }

    public void setRelacao(List<?> list)
    {
        for(PRelacao e : this._relacao_)
        {
            e.parent(null);
        }
        this._relacao_.clear();

        for(Object obj_e : list)
        {
            PRelacao e = (PRelacao) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._relacao_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._relacao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._relacao_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PRelacao> i = this._relacao_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PRelacao) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
