/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AInteiroExpressao extends PExpressao
{
    private TValorInteiro _valorInteiro_;

    public AInteiroExpressao()
    {
        // Constructor
    }

    public AInteiroExpressao(
        @SuppressWarnings("hiding") TValorInteiro _valorInteiro_)
    {
        // Constructor
        setValorInteiro(_valorInteiro_);

    }

    @Override
    public Object clone()
    {
        return new AInteiroExpressao(
            cloneNode(this._valorInteiro_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInteiroExpressao(this);
    }

    public TValorInteiro getValorInteiro()
    {
        return this._valorInteiro_;
    }

    public void setValorInteiro(TValorInteiro node)
    {
        if(this._valorInteiro_ != null)
        {
            this._valorInteiro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valorInteiro_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._valorInteiro_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._valorInteiro_ == child)
        {
            this._valorInteiro_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._valorInteiro_ == oldChild)
        {
            setValorInteiro((TValorInteiro) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
