/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ALacoComando extends PComando
{
    private TAs _abreAs_;
    private TLong _long_;
    private TAs _fechaAs_;
    private TParEsq _parEsq_;
    private PExpressao _expressao_;
    private TParDir _parDir_;
    private PBlocoComandos _blocoComandos_;

    public ALacoComando()
    {
        // Constructor
    }

    public ALacoComando(
        @SuppressWarnings("hiding") TAs _abreAs_,
        @SuppressWarnings("hiding") TLong _long_,
        @SuppressWarnings("hiding") TAs _fechaAs_,
        @SuppressWarnings("hiding") TParEsq _parEsq_,
        @SuppressWarnings("hiding") PExpressao _expressao_,
        @SuppressWarnings("hiding") TParDir _parDir_,
        @SuppressWarnings("hiding") PBlocoComandos _blocoComandos_)
    {
        // Constructor
        setAbreAs(_abreAs_);

        setLong(_long_);

        setFechaAs(_fechaAs_);

        setParEsq(_parEsq_);

        setExpressao(_expressao_);

        setParDir(_parDir_);

        setBlocoComandos(_blocoComandos_);

    }

    @Override
    public Object clone()
    {
        return new ALacoComando(
            cloneNode(this._abreAs_),
            cloneNode(this._long_),
            cloneNode(this._fechaAs_),
            cloneNode(this._parEsq_),
            cloneNode(this._expressao_),
            cloneNode(this._parDir_),
            cloneNode(this._blocoComandos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALacoComando(this);
    }

    public TAs getAbreAs()
    {
        return this._abreAs_;
    }

    public void setAbreAs(TAs node)
    {
        if(this._abreAs_ != null)
        {
            this._abreAs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._abreAs_ = node;
    }

    public TLong getLong()
    {
        return this._long_;
    }

    public void setLong(TLong node)
    {
        if(this._long_ != null)
        {
            this._long_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._long_ = node;
    }

    public TAs getFechaAs()
    {
        return this._fechaAs_;
    }

    public void setFechaAs(TAs node)
    {
        if(this._fechaAs_ != null)
        {
            this._fechaAs_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fechaAs_ = node;
    }

    public TParEsq getParEsq()
    {
        return this._parEsq_;
    }

    public void setParEsq(TParEsq node)
    {
        if(this._parEsq_ != null)
        {
            this._parEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parEsq_ = node;
    }

    public PExpressao getExpressao()
    {
        return this._expressao_;
    }

    public void setExpressao(PExpressao node)
    {
        if(this._expressao_ != null)
        {
            this._expressao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressao_ = node;
    }

    public TParDir getParDir()
    {
        return this._parDir_;
    }

    public void setParDir(TParDir node)
    {
        if(this._parDir_ != null)
        {
            this._parDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parDir_ = node;
    }

    public PBlocoComandos getBlocoComandos()
    {
        return this._blocoComandos_;
    }

    public void setBlocoComandos(PBlocoComandos node)
    {
        if(this._blocoComandos_ != null)
        {
            this._blocoComandos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._blocoComandos_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._abreAs_)
            + toString(this._long_)
            + toString(this._fechaAs_)
            + toString(this._parEsq_)
            + toString(this._expressao_)
            + toString(this._parDir_)
            + toString(this._blocoComandos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._abreAs_ == child)
        {
            this._abreAs_ = null;
            return;
        }

        if(this._long_ == child)
        {
            this._long_ = null;
            return;
        }

        if(this._fechaAs_ == child)
        {
            this._fechaAs_ = null;
            return;
        }

        if(this._parEsq_ == child)
        {
            this._parEsq_ = null;
            return;
        }

        if(this._expressao_ == child)
        {
            this._expressao_ = null;
            return;
        }

        if(this._parDir_ == child)
        {
            this._parDir_ = null;
            return;
        }

        if(this._blocoComandos_ == child)
        {
            this._blocoComandos_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._abreAs_ == oldChild)
        {
            setAbreAs((TAs) newChild);
            return;
        }

        if(this._long_ == oldChild)
        {
            setLong((TLong) newChild);
            return;
        }

        if(this._fechaAs_ == oldChild)
        {
            setFechaAs((TAs) newChild);
            return;
        }

        if(this._parEsq_ == oldChild)
        {
            setParEsq((TParEsq) newChild);
            return;
        }

        if(this._expressao_ == oldChild)
        {
            setExpressao((PExpressao) newChild);
            return;
        }

        if(this._parDir_ == oldChild)
        {
            setParDir((TParDir) newChild);
            return;
        }

        if(this._blocoComandos_ == oldChild)
        {
            setBlocoComandos((PBlocoComandos) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
