/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ALacoComando extends PComando
{
    private PExpressao _expressao_;
    private PBlocoComandos _blocoComandos_;

    public ALacoComando()
    {
        // Constructor
    }

    public ALacoComando(
        @SuppressWarnings("hiding") PExpressao _expressao_,
        @SuppressWarnings("hiding") PBlocoComandos _blocoComandos_)
    {
        // Constructor
        setExpressao(_expressao_);

        setBlocoComandos(_blocoComandos_);

    }

    @Override
    public Object clone()
    {
        return new ALacoComando(
            cloneNode(this._expressao_),
            cloneNode(this._blocoComandos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALacoComando(this);
    }

    public PExpressao getExpressao()
    {
        return this._expressao_;
    }

    public void setExpressao(PExpressao node)
    {
        if(this._expressao_ != null)
        {
            this._expressao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressao_ = node;
    }

    public PBlocoComandos getBlocoComandos()
    {
        return this._blocoComandos_;
    }

    public void setBlocoComandos(PBlocoComandos node)
    {
        if(this._blocoComandos_ != null)
        {
            this._blocoComandos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._blocoComandos_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressao_)
            + toString(this._blocoComandos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressao_ == child)
        {
            this._expressao_ = null;
            return;
        }

        if(this._blocoComandos_ == child)
        {
            this._blocoComandos_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressao_ == oldChild)
        {
            setExpressao((PExpressao) newChild);
            return;
        }

        if(this._blocoComandos_ == oldChild)
        {
            setBlocoComandos((PBlocoComandos) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
