/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AMultiplosListaDecLocal extends PListaDecLocal
{
    private PListaDecLocal _listaDecLocal_;
    private PDecLocal _decLocal_;

    public AMultiplosListaDecLocal()
    {
        // Constructor
    }

    public AMultiplosListaDecLocal(
        @SuppressWarnings("hiding") PListaDecLocal _listaDecLocal_,
        @SuppressWarnings("hiding") PDecLocal _decLocal_)
    {
        // Constructor
        setListaDecLocal(_listaDecLocal_);

        setDecLocal(_decLocal_);

    }

    @Override
    public Object clone()
    {
        return new AMultiplosListaDecLocal(
            cloneNode(this._listaDecLocal_),
            cloneNode(this._decLocal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiplosListaDecLocal(this);
    }

    public PListaDecLocal getListaDecLocal()
    {
        return this._listaDecLocal_;
    }

    public void setListaDecLocal(PListaDecLocal node)
    {
        if(this._listaDecLocal_ != null)
        {
            this._listaDecLocal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaDecLocal_ = node;
    }

    public PDecLocal getDecLocal()
    {
        return this._decLocal_;
    }

    public void setDecLocal(PDecLocal node)
    {
        if(this._decLocal_ != null)
        {
            this._decLocal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decLocal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listaDecLocal_)
            + toString(this._decLocal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listaDecLocal_ == child)
        {
            this._listaDecLocal_ = null;
            return;
        }

        if(this._decLocal_ == child)
        {
            this._decLocal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listaDecLocal_ == oldChild)
        {
            setListaDecLocal((PListaDecLocal) newChild);
            return;
        }

        if(this._decLocal_ == oldChild)
        {
            setDecLocal((PDecLocal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
