/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AMultiplosListaComando extends PListaComando
{
    private PListaComando _listaComando_;
    private PComando _comando_;

    public AMultiplosListaComando()
    {
        // Constructor
    }

    public AMultiplosListaComando(
        @SuppressWarnings("hiding") PListaComando _listaComando_,
        @SuppressWarnings("hiding") PComando _comando_)
    {
        // Constructor
        setListaComando(_listaComando_);

        setComando(_comando_);

    }

    @Override
    public Object clone()
    {
        return new AMultiplosListaComando(
            cloneNode(this._listaComando_),
            cloneNode(this._comando_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiplosListaComando(this);
    }

    public PListaComando getListaComando()
    {
        return this._listaComando_;
    }

    public void setListaComando(PListaComando node)
    {
        if(this._listaComando_ != null)
        {
            this._listaComando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaComando_ = node;
    }

    public PComando getComando()
    {
        return this._comando_;
    }

    public void setComando(PComando node)
    {
        if(this._comando_ != null)
        {
            this._comando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comando_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listaComando_)
            + toString(this._comando_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listaComando_ == child)
        {
            this._listaComando_ = null;
            return;
        }

        if(this._comando_ == child)
        {
            this._comando_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listaComando_ == oldChild)
        {
            setListaComando((PListaComando) newChild);
            return;
        }

        if(this._comando_ == oldChild)
        {
            setComando((PComando) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
