/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AMultiplasListaDefinicaoCorpo extends PListaDefinicaoCorpo
{
    private PListaDefinicaoCorpo _listaDefinicaoCorpo_;
    private PDeclaracaoClasse _declaracaoClasse_;

    public AMultiplasListaDefinicaoCorpo()
    {
        // Constructor
    }

    public AMultiplasListaDefinicaoCorpo(
        @SuppressWarnings("hiding") PListaDefinicaoCorpo _listaDefinicaoCorpo_,
        @SuppressWarnings("hiding") PDeclaracaoClasse _declaracaoClasse_)
    {
        // Constructor
        setListaDefinicaoCorpo(_listaDefinicaoCorpo_);

        setDeclaracaoClasse(_declaracaoClasse_);

    }

    @Override
    public Object clone()
    {
        return new AMultiplasListaDefinicaoCorpo(
            cloneNode(this._listaDefinicaoCorpo_),
            cloneNode(this._declaracaoClasse_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiplasListaDefinicaoCorpo(this);
    }

    public PListaDefinicaoCorpo getListaDefinicaoCorpo()
    {
        return this._listaDefinicaoCorpo_;
    }

    public void setListaDefinicaoCorpo(PListaDefinicaoCorpo node)
    {
        if(this._listaDefinicaoCorpo_ != null)
        {
            this._listaDefinicaoCorpo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaDefinicaoCorpo_ = node;
    }

    public PDeclaracaoClasse getDeclaracaoClasse()
    {
        return this._declaracaoClasse_;
    }

    public void setDeclaracaoClasse(PDeclaracaoClasse node)
    {
        if(this._declaracaoClasse_ != null)
        {
            this._declaracaoClasse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracaoClasse_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listaDefinicaoCorpo_)
            + toString(this._declaracaoClasse_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listaDefinicaoCorpo_ == child)
        {
            this._listaDefinicaoCorpo_ = null;
            return;
        }

        if(this._declaracaoClasse_ == child)
        {
            this._declaracaoClasse_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listaDefinicaoCorpo_ == oldChild)
        {
            setListaDefinicaoCorpo((PListaDefinicaoCorpo) newChild);
            return;
        }

        if(this._declaracaoClasse_ == oldChild)
        {
            setDeclaracaoClasse((PDeclaracaoClasse) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
