/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AMultiplosListaMaisExp extends PListaMaisExp
{
    private PListaMaisExp _listaMaisExp_;
    private PMaisExp _maisExp_;

    public AMultiplosListaMaisExp()
    {
        // Constructor
    }

    public AMultiplosListaMaisExp(
        @SuppressWarnings("hiding") PListaMaisExp _listaMaisExp_,
        @SuppressWarnings("hiding") PMaisExp _maisExp_)
    {
        // Constructor
        setListaMaisExp(_listaMaisExp_);

        setMaisExp(_maisExp_);

    }

    @Override
    public Object clone()
    {
        return new AMultiplosListaMaisExp(
            cloneNode(this._listaMaisExp_),
            cloneNode(this._maisExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiplosListaMaisExp(this);
    }

    public PListaMaisExp getListaMaisExp()
    {
        return this._listaMaisExp_;
    }

    public void setListaMaisExp(PListaMaisExp node)
    {
        if(this._listaMaisExp_ != null)
        {
            this._listaMaisExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaMaisExp_ = node;
    }

    public PMaisExp getMaisExp()
    {
        return this._maisExp_;
    }

    public void setMaisExp(PMaisExp node)
    {
        if(this._maisExp_ != null)
        {
            this._maisExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maisExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listaMaisExp_)
            + toString(this._maisExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listaMaisExp_ == child)
        {
            this._listaMaisExp_ = null;
            return;
        }

        if(this._maisExp_ == child)
        {
            this._maisExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listaMaisExp_ == oldChild)
        {
            setListaMaisExp((PListaMaisExp) newChild);
            return;
        }

        if(this._maisExp_ == oldChild)
        {
            setMaisExp((PMaisExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
