/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AMultiplosListaComponentes extends PListaComponentes
{
    private PListaComponentes _listaComponentes_;
    private PComponentes _componentes_;

    public AMultiplosListaComponentes()
    {
        // Constructor
    }

    public AMultiplosListaComponentes(
        @SuppressWarnings("hiding") PListaComponentes _listaComponentes_,
        @SuppressWarnings("hiding") PComponentes _componentes_)
    {
        // Constructor
        setListaComponentes(_listaComponentes_);

        setComponentes(_componentes_);

    }

    @Override
    public Object clone()
    {
        return new AMultiplosListaComponentes(
            cloneNode(this._listaComponentes_),
            cloneNode(this._componentes_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiplosListaComponentes(this);
    }

    public PListaComponentes getListaComponentes()
    {
        return this._listaComponentes_;
    }

    public void setListaComponentes(PListaComponentes node)
    {
        if(this._listaComponentes_ != null)
        {
            this._listaComponentes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaComponentes_ = node;
    }

    public PComponentes getComponentes()
    {
        return this._componentes_;
    }

    public void setComponentes(PComponentes node)
    {
        if(this._componentes_ != null)
        {
            this._componentes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._componentes_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listaComponentes_)
            + toString(this._componentes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listaComponentes_ == child)
        {
            this._listaComponentes_ = null;
            return;
        }

        if(this._componentes_ == child)
        {
            this._componentes_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listaComponentes_ == oldChild)
        {
            setListaComponentes((PListaComponentes) newChild);
            return;
        }

        if(this._componentes_ == oldChild)
        {
            setComponentes((PComponentes) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
