/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AOuExpressaoOu extends PExpressaoOu
{
    private PExpressaoOu _expressaoOu_;
    private TOr _or_;
    private PExpressaoAnd _expressaoAnd_;

    public AOuExpressaoOu()
    {
        // Constructor
    }

    public AOuExpressaoOu(
        @SuppressWarnings("hiding") PExpressaoOu _expressaoOu_,
        @SuppressWarnings("hiding") TOr _or_,
        @SuppressWarnings("hiding") PExpressaoAnd _expressaoAnd_)
    {
        // Constructor
        setExpressaoOu(_expressaoOu_);

        setOr(_or_);

        setExpressaoAnd(_expressaoAnd_);

    }

    @Override
    public Object clone()
    {
        return new AOuExpressaoOu(
            cloneNode(this._expressaoOu_),
            cloneNode(this._or_),
            cloneNode(this._expressaoAnd_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOuExpressaoOu(this);
    }

    public PExpressaoOu getExpressaoOu()
    {
        return this._expressaoOu_;
    }

    public void setExpressaoOu(PExpressaoOu node)
    {
        if(this._expressaoOu_ != null)
        {
            this._expressaoOu_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoOu_ = node;
    }

    public TOr getOr()
    {
        return this._or_;
    }

    public void setOr(TOr node)
    {
        if(this._or_ != null)
        {
            this._or_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._or_ = node;
    }

    public PExpressaoAnd getExpressaoAnd()
    {
        return this._expressaoAnd_;
    }

    public void setExpressaoAnd(PExpressaoAnd node)
    {
        if(this._expressaoAnd_ != null)
        {
            this._expressaoAnd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoAnd_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressaoOu_)
            + toString(this._or_)
            + toString(this._expressaoAnd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressaoOu_ == child)
        {
            this._expressaoOu_ = null;
            return;
        }

        if(this._or_ == child)
        {
            this._or_ = null;
            return;
        }

        if(this._expressaoAnd_ == child)
        {
            this._expressaoAnd_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressaoOu_ == oldChild)
        {
            setExpressaoOu((PExpressaoOu) newChild);
            return;
        }

        if(this._or_ == oldChild)
        {
            setOr((TOr) newChild);
            return;
        }

        if(this._expressaoAnd_ == oldChild)
        {
            setExpressaoAnd((PExpressaoAnd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
