/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class APrefixoAcesso extends PPrefixoAcesso
{
    private TId _id_;
    private TSeta _seta_;

    public APrefixoAcesso()
    {
        // Constructor
    }

    public APrefixoAcesso(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TSeta _seta_)
    {
        // Constructor
        setId(_id_);

        setSeta(_seta_);

    }

    @Override
    public Object clone()
    {
        return new APrefixoAcesso(
            cloneNode(this._id_),
            cloneNode(this._seta_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrefixoAcesso(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TSeta getSeta()
    {
        return this._seta_;
    }

    public void setSeta(TSeta node)
    {
        if(this._seta_ != null)
        {
            this._seta_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._seta_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._seta_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._seta_ == child)
        {
            this._seta_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._seta_ == oldChild)
        {
            setSeta((TSeta) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
