/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import java.util.*;
import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AProcedimentoAbstMetodo extends PMetodo
{
    private TMarcadorEntrada _marcador_;
    private TId _id_;
    private final LinkedList<PParametro> _parametro_ = new LinkedList<PParametro>();

    public AProcedimentoAbstMetodo()
    {
        // Constructor
    }

    public AProcedimentoAbstMetodo(
        @SuppressWarnings("hiding") TMarcadorEntrada _marcador_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") List<?> _parametro_)
    {
        // Constructor
        setMarcador(_marcador_);

        setId(_id_);

        setParametro(_parametro_);

    }

    @Override
    public Object clone()
    {
        return new AProcedimentoAbstMetodo(
            cloneNode(this._marcador_),
            cloneNode(this._id_),
            cloneList(this._parametro_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProcedimentoAbstMetodo(this);
    }

    public TMarcadorEntrada getMarcador()
    {
        return this._marcador_;
    }

    public void setMarcador(TMarcadorEntrada node)
    {
        if(this._marcador_ != null)
        {
            this._marcador_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._marcador_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public LinkedList<PParametro> getParametro()
    {
        return this._parametro_;
    }

    public void setParametro(List<?> list)
    {
        for(PParametro e : this._parametro_)
        {
            e.parent(null);
        }
        this._parametro_.clear();

        for(Object obj_e : list)
        {
            PParametro e = (PParametro) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._parametro_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._marcador_)
            + toString(this._id_)
            + toString(this._parametro_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._marcador_ == child)
        {
            this._marcador_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._parametro_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._marcador_ == oldChild)
        {
            setMarcador((TMarcadorEntrada) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator<PParametro> i = this._parametro_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PParametro) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
