/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class AProcedimentoConcrMetodo extends PMetodo
{
    private TProcedure _procedure_;
    private POptMarcadorEntrada _optMarcadorEntrada_;
    private TId _id_;
    private TColcEsq _colcEsq_;
    private POptParametros _optParametros_;
    private TColcDir _colcDir_;
    private PBlocoComandos _blocoComandos_;

    public AProcedimentoConcrMetodo()
    {
        // Constructor
    }

    public AProcedimentoConcrMetodo(
        @SuppressWarnings("hiding") TProcedure _procedure_,
        @SuppressWarnings("hiding") POptMarcadorEntrada _optMarcadorEntrada_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TColcEsq _colcEsq_,
        @SuppressWarnings("hiding") POptParametros _optParametros_,
        @SuppressWarnings("hiding") TColcDir _colcDir_,
        @SuppressWarnings("hiding") PBlocoComandos _blocoComandos_)
    {
        // Constructor
        setProcedure(_procedure_);

        setOptMarcadorEntrada(_optMarcadorEntrada_);

        setId(_id_);

        setColcEsq(_colcEsq_);

        setOptParametros(_optParametros_);

        setColcDir(_colcDir_);

        setBlocoComandos(_blocoComandos_);

    }

    @Override
    public Object clone()
    {
        return new AProcedimentoConcrMetodo(
            cloneNode(this._procedure_),
            cloneNode(this._optMarcadorEntrada_),
            cloneNode(this._id_),
            cloneNode(this._colcEsq_),
            cloneNode(this._optParametros_),
            cloneNode(this._colcDir_),
            cloneNode(this._blocoComandos_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProcedimentoConcrMetodo(this);
    }

    public TProcedure getProcedure()
    {
        return this._procedure_;
    }

    public void setProcedure(TProcedure node)
    {
        if(this._procedure_ != null)
        {
            this._procedure_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._procedure_ = node;
    }

    public POptMarcadorEntrada getOptMarcadorEntrada()
    {
        return this._optMarcadorEntrada_;
    }

    public void setOptMarcadorEntrada(POptMarcadorEntrada node)
    {
        if(this._optMarcadorEntrada_ != null)
        {
            this._optMarcadorEntrada_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._optMarcadorEntrada_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TColcEsq getColcEsq()
    {
        return this._colcEsq_;
    }

    public void setColcEsq(TColcEsq node)
    {
        if(this._colcEsq_ != null)
        {
            this._colcEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colcEsq_ = node;
    }

    public POptParametros getOptParametros()
    {
        return this._optParametros_;
    }

    public void setOptParametros(POptParametros node)
    {
        if(this._optParametros_ != null)
        {
            this._optParametros_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._optParametros_ = node;
    }

    public TColcDir getColcDir()
    {
        return this._colcDir_;
    }

    public void setColcDir(TColcDir node)
    {
        if(this._colcDir_ != null)
        {
            this._colcDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colcDir_ = node;
    }

    public PBlocoComandos getBlocoComandos()
    {
        return this._blocoComandos_;
    }

    public void setBlocoComandos(PBlocoComandos node)
    {
        if(this._blocoComandos_ != null)
        {
            this._blocoComandos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._blocoComandos_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._procedure_)
            + toString(this._optMarcadorEntrada_)
            + toString(this._id_)
            + toString(this._colcEsq_)
            + toString(this._optParametros_)
            + toString(this._colcDir_)
            + toString(this._blocoComandos_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._procedure_ == child)
        {
            this._procedure_ = null;
            return;
        }

        if(this._optMarcadorEntrada_ == child)
        {
            this._optMarcadorEntrada_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._colcEsq_ == child)
        {
            this._colcEsq_ = null;
            return;
        }

        if(this._optParametros_ == child)
        {
            this._optParametros_ = null;
            return;
        }

        if(this._colcDir_ == child)
        {
            this._colcDir_ = null;
            return;
        }

        if(this._blocoComandos_ == child)
        {
            this._blocoComandos_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._procedure_ == oldChild)
        {
            setProcedure((TProcedure) newChild);
            return;
        }

        if(this._optMarcadorEntrada_ == oldChild)
        {
            setOptMarcadorEntrada((POptMarcadorEntrada) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._colcEsq_ == oldChild)
        {
            setColcEsq((TColcEsq) newChild);
            return;
        }

        if(this._optParametros_ == oldChild)
        {
            setOptParametros((POptParametros) newChild);
            return;
        }

        if(this._colcDir_ == oldChild)
        {
            setColcDir((TColcDir) newChild);
            return;
        }

        if(this._blocoComandos_ == oldChild)
        {
            setBlocoComandos((PBlocoComandos) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
