/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class APrograma extends PPrograma
{
    private POptGenealogia _optGenealogia_;
    private PListaDefinicaoCorpo _listaDefinicaoCorpo_;

    public APrograma()
    {
        // Constructor
    }

    public APrograma(
        @SuppressWarnings("hiding") POptGenealogia _optGenealogia_,
        @SuppressWarnings("hiding") PListaDefinicaoCorpo _listaDefinicaoCorpo_)
    {
        // Constructor
        setOptGenealogia(_optGenealogia_);

        setListaDefinicaoCorpo(_listaDefinicaoCorpo_);

    }

    @Override
    public Object clone()
    {
        return new APrograma(
            cloneNode(this._optGenealogia_),
            cloneNode(this._listaDefinicaoCorpo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrograma(this);
    }

    public POptGenealogia getOptGenealogia()
    {
        return this._optGenealogia_;
    }

    public void setOptGenealogia(POptGenealogia node)
    {
        if(this._optGenealogia_ != null)
        {
            this._optGenealogia_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._optGenealogia_ = node;
    }

    public PListaDefinicaoCorpo getListaDefinicaoCorpo()
    {
        return this._listaDefinicaoCorpo_;
    }

    public void setListaDefinicaoCorpo(PListaDefinicaoCorpo node)
    {
        if(this._listaDefinicaoCorpo_ != null)
        {
            this._listaDefinicaoCorpo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listaDefinicaoCorpo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._optGenealogia_)
            + toString(this._listaDefinicaoCorpo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._optGenealogia_ == child)
        {
            this._optGenealogia_ = null;
            return;
        }

        if(this._listaDefinicaoCorpo_ == child)
        {
            this._listaDefinicaoCorpo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._optGenealogia_ == oldChild)
        {
            setOptGenealogia((POptGenealogia) newChild);
            return;
        }

        if(this._listaDefinicaoCorpo_ == oldChild)
        {
            setListaDefinicaoCorpo((PListaDefinicaoCorpo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
