/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ARealExpressao extends PExpressao
{
    private TValorReal _valorReal_;

    public ARealExpressao()
    {
        // Constructor
    }

    public ARealExpressao(
        @SuppressWarnings("hiding") TValorReal _valorReal_)
    {
        // Constructor
        setValorReal(_valorReal_);

    }

    @Override
    public Object clone()
    {
        return new ARealExpressao(
            cloneNode(this._valorReal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARealExpressao(this);
    }

    public TValorReal getValorReal()
    {
        return this._valorReal_;
    }

    public void setValorReal(TValorReal node)
    {
        if(this._valorReal_ != null)
        {
            this._valorReal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valorReal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._valorReal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._valorReal_ == child)
        {
            this._valorReal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._valorReal_ == oldChild)
        {
            setValorReal((TValorReal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
