/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class ARetornoComando extends PComando
{
    private TFinish _finish_;
    private POptExpressao _optExpressao_;
    private TPonto _ponto_;

    public ARetornoComando()
    {
        // Constructor
    }

    public ARetornoComando(
        @SuppressWarnings("hiding") TFinish _finish_,
        @SuppressWarnings("hiding") POptExpressao _optExpressao_,
        @SuppressWarnings("hiding") TPonto _ponto_)
    {
        // Constructor
        setFinish(_finish_);

        setOptExpressao(_optExpressao_);

        setPonto(_ponto_);

    }

    @Override
    public Object clone()
    {
        return new ARetornoComando(
            cloneNode(this._finish_),
            cloneNode(this._optExpressao_),
            cloneNode(this._ponto_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARetornoComando(this);
    }

    public TFinish getFinish()
    {
        return this._finish_;
    }

    public void setFinish(TFinish node)
    {
        if(this._finish_ != null)
        {
            this._finish_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._finish_ = node;
    }

    public POptExpressao getOptExpressao()
    {
        return this._optExpressao_;
    }

    public void setOptExpressao(POptExpressao node)
    {
        if(this._optExpressao_ != null)
        {
            this._optExpressao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._optExpressao_ = node;
    }

    public TPonto getPonto()
    {
        return this._ponto_;
    }

    public void setPonto(TPonto node)
    {
        if(this._ponto_ != null)
        {
            this._ponto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ponto_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._finish_)
            + toString(this._optExpressao_)
            + toString(this._ponto_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._finish_ == child)
        {
            this._finish_ = null;
            return;
        }

        if(this._optExpressao_ == child)
        {
            this._optExpressao_ = null;
            return;
        }

        if(this._ponto_ == child)
        {
            this._ponto_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._finish_ == oldChild)
        {
            setFinish((TFinish) newChild);
            return;
        }

        if(this._optExpressao_ == oldChild)
        {
            setOptExpressao((POptExpressao) newChild);
            return;
        }

        if(this._ponto_ == oldChild)
        {
            setPonto((TPonto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
