/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TAlterable extends Token
{
    public TAlterable()
    {
        super.setText("alterable");
    }

    public TAlterable(int line, int pos)
    {
        super.setText("alterable");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAlterable(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAlterable(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAlterable text.");
    }
}
