/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TAnswer extends Token
{
    public TAnswer()
    {
        super.setText("answer");
    }

    public TAnswer(int line, int pos)
    {
        super.setText("answer");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAnswer(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAnswer(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAnswer text.");
    }
}
