/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TDerivesFrom extends Token
{
    public TDerivesFrom()
    {
        super.setText("derives from");
    }

    public TDerivesFrom(int line, int pos)
    {
        super.setText("derives from");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDerivesFrom(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDerivesFrom(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDerivesFrom text.");
    }
}
