/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TDerives extends Token
{
    public TDerives()
    {
        super.setText("derives");
    }

    public TDerives(int line, int pos)
    {
        super.setText("derives");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDerives(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDerives(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDerives text.");
    }
}
