/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TFamily extends Token
{
    public TFamily()
    {
        super.setText("family");
    }

    public TFamily(int line, int pos)
    {
        super.setText("family");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFamily(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFamily(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFamily text.");
    }
}
