/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TInCaseThat extends Token
{
    public TInCaseThat()
    {
        super.setText("in case that");
    }

    public TInCaseThat(int line, int pos)
    {
        super.setText("in case that");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TInCaseThat(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTInCaseThat(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TInCaseThat text.");
    }
}
