/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.node;

import dplusplus.analysis.*;

@SuppressWarnings("nls")
public final class TYes extends Token
{
    public TYes()
    {
        super.setText("yes");
    }

    public TYes(int line, int pos)
    {
        super.setText("yes");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TYes(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTYes(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TYes text.");
    }
}
