/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.analysis;

import dplusplus.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAGenealogia(AGenealogia node);
    void caseAMaisRelacao(AMaisRelacao node);
    void caseARelacao(ARelacao node);
    void caseATipoClasse(ATipoClasse node);

    void caseTValorReal(TValorReal node);
    void caseTValorInteiro(TValorInteiro node);
    void caseTYes(TYes node);
    void caseTNo(TNo node);
    void caseTSoma(TSoma node);
    void caseTMenos(TMenos node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTIgual(TIgual node);
    void caseTMenor(TMenor node);
    void caseTMaior(TMaior node);
    void caseTNao(TNao node);
    void caseTAnd(TAnd node);
    void caseTOr(TOr node);
    void caseTAcesso(TAcesso node);
    void caseTAtribuicao(TAtribuicao node);
    void caseTPonto(TPonto node);
    void caseTEComercial(TEComercial node);
    void caseTPipe(TPipe node);
    void caseTParEsq(TParEsq node);
    void caseTParDir(TParDir node);
    void caseTColcEsq(TColcEsq node);
    void caseTColcDir(TColcDir node);
    void caseTFinish(TFinish node);
    void caseTStart(TStart node);
    void caseTIn(TIn node);
    void caseTCase(TCase node);
    void caseTThat(TThat node);
    void caseTAs(TAs node);
    void caseTLong(TLong node);
    void caseTOtherwise(TOtherwise node);
    void caseTIf(TIf node);
    void caseTElse(TElse node);
    void caseTFamily(TFamily node);
    void caseTDerives(TDerives node);
    void caseTFrom(TFrom node);
    void caseTObject(TObject node);
    void caseTFunction(TFunction node);
    void caseTProcedure(TProcedure node);
    void caseTAlterable(TAlterable node);
    void caseTUnalterable(TUnalterable node);
    void caseTAnswer(TAnswer node);
    void caseTNumber(TNumber node);
    void caseTMarcadorEntrada(TMarcadorEntrada node);
    void caseTIdClasse(TIdClasse node);
    void caseTId(TId node);
    void caseTVazio(TVazio node);
    void caseTComentLinha(TComentLinha node);
    void caseTComentBloco(TComentBloco node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
