/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.analysis;

import java.util.*;
import dplusplus.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPrograma(APrograma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComGenealogiaOptGenealogia(AComGenealogiaOptGenealogia node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASemGenealogiaOptGenealogia(ASemGenealogiaOptGenealogia node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultiplasListaDefinicaoCorpo(AMultiplasListaDefinicaoCorpo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABaseListaDefinicaoCorpo(ABaseListaDefinicaoCorpo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAGenealogia(AGenealogia node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultiplasListaMaisRelacao(AMultiplasListaMaisRelacao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABaseListaMaisRelacao(ABaseListaMaisRelacao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMaisRelacao(AMaisRelacao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARelacao(ARelacao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADeclaracaoClasse(ADeclaracaoClasse node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultiplosListaComponentes(AMultiplosListaComponentes node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABaseListaComponentes(ABaseListaComponentes node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVarComponentes(AVarComponentes node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAConsComponentes(AConsComponentes node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAObjComponentes(AObjComponentes node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMetodoComponentes(AMetodoComponentes node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADecVar(ADecVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADecCons(ADecCons node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADecObj(ADecObj node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInteiroTipoPrimitivo(AInteiroTipoPrimitivo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABooleanoTipoPrimitivo(ABooleanoTipoPrimitivo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPrimitivoTipo(APrimitivoTipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAClasseTipo(AClasseTipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFuncaoConcretaMetodo(AFuncaoConcretaMetodo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFuncaoAbstrataMetodo(AFuncaoAbstrataMetodo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAProcedimentoConcrMetodo(AProcedimentoConcrMetodo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAProcedimentoAbstMetodo(AProcedimentoAbstMetodo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComMarcadorOptMarcadorEntrada(AComMarcadorOptMarcadorEntrada node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASemMarcadorOptMarcadorEntrada(ASemMarcadorOptMarcadorEntrada node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComParametrosOptParametros(AComParametrosOptParametros node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASemParametrosOptParametros(ASemParametrosOptParametros node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParametros(AParametros node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultiplosListaMaisParametros(AMultiplosListaMaisParametros node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABaseListaMaisParametros(ABaseListaMaisParametros node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMaisParametros(AMaisParametros node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParametro(AParametro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABlocoComandos(ABlocoComandos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABlocoExp(ABlocoExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultiplosListaDecLocal(AMultiplosListaDecLocal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABaseListaDecLocal(ABaseListaDecLocal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVarDecLocal(AVarDecLocal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAConsDecLocal(AConsDecLocal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAObjDecLocal(AObjDecLocal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultiplosListaComando(AMultiplosListaComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABaseListaComando(ABaseListaComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAtribuicaoComando(AAtribuicaoComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAChamadaCmdComando(AChamadaCmdComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACondicionalComando(ACondicionalComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALacoComando(ALacoComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABlocoComando(ABlocoComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComOtherwiseOptCmdOtherwise(AComOtherwiseOptCmdOtherwise node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASemOtherwiseOptCmdOtherwise(ASemOtherwiseOptCmdOtherwise node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComExpressaoOptExpressao(AComExpressaoOptExpressao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASemExpressaoOptExpressao(ASemExpressaoOptExpressao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATernarioExprExpressao(ATernarioExprExpressao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASimplesExpressao(ASimplesExpressao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOuExpressaoOu(AOuExpressaoOu node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASimplesExpressaoOu(ASimplesExpressaoOu node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEExpressaoAnd(AEExpressaoAnd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASimplesExpressaoAnd(ASimplesExpressaoAnd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMenorExpressaoRelacional(AMenorExpressaoRelacional node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMaiorExpressaoRelacional(AMaiorExpressaoRelacional node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIgualExpressaoRelacional(AIgualExpressaoRelacional node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASimplesExpressaoRelacional(ASimplesExpressaoRelacional node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASomaExpressaoAritmetica(ASomaExpressaoAritmetica node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASubtracaoExpressaoAritmetica(ASubtracaoExpressaoAritmetica node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASimplesExpressaoAritmetica(ASimplesExpressaoAritmetica node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultiplicacaoTermo(AMultiplicacaoTermo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADivisaoTermo(ADivisaoTermo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASimplesTermo(ASimplesTermo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIdFator(AIdFator node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInteiroFator(AInteiroFator node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARealFator(ARealFator node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABooleanoVFator(ABooleanoVFator node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABooleanoFFator(ABooleanoFFator node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANegacaoFator(ANegacaoFator node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMenosUnarioFator(AMenosUnarioFator node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAcessoSetaFator(AAcessoSetaFator node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAChamadaExprFator(AChamadaExprFator node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParentesesFator(AParentesesFator node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultiplosListaPrefixoAcesso(AMultiplosListaPrefixoAcesso node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABaseListaPrefixoAcesso(ABaseListaPrefixoAcesso node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComAcessoOptListaPrefixoAcesso(AComAcessoOptListaPrefixoAcesso node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASemAcessoOptListaPrefixoAcesso(ASemAcessoOptListaPrefixoAcesso node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPrefixoAcesso(APrefixoAcesso node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComExpOptListaExp(AComExpOptListaExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASemExpOptListaExp(ASemExpOptListaExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAListaExp(AListaExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultiplosListaMaisExp(AMultiplosListaMaisExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABaseListaMaisExp(ABaseListaMaisExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMaisExp(AMaisExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTValorReal(TValorReal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTValorInteiro(TValorInteiro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTYes(TYes node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNo(TNo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSoma(TSoma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMenos(TMenos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMult(TMult node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDiv(TDiv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIgual(TIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMenor(TMenor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMaior(TMaior node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNao(TNao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAnd(TAnd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOr(TOr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSeta(TSeta node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAtribuicao(TAtribuicao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPonto(TPonto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEComercial(TEComercial node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPipe(TPipe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParEsq(TParEsq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParDir(TParDir node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTColcEsq(TColcEsq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTColcDir(TColcDir node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFinish(TFinish node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTStart(TStart node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIn(TIn node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCase(TCase node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTThat(TThat node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAs(TAs node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLong(TLong node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOtherwise(TOtherwise node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIf(TIf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTElse(TElse node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFamily(TFamily node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDerives(TDerives node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFrom(TFrom node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTObject(TObject node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFunction(TFunction node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTProcedure(TProcedure node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAlterable(TAlterable node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTUnalterable(TUnalterable node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAnswer(TAnswer node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNumber(TNumber node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMarcadorEntrada(TMarcadorEntrada node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIdClasse(TIdClasse node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTId(TId node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVazio(TVazio node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComentLinha(TComentLinha node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComentBloco(TComentBloco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
