/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.analysis;

import java.util.*;
import dplusplus.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPPrograma().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inAPrograma(APrograma node)
    {
        defaultIn(node);
    }

    public void outAPrograma(APrograma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrograma(APrograma node)
    {
        inAPrograma(node);
        if(node.getOptGenealogia() != null)
        {
            node.getOptGenealogia().apply(this);
        }
        if(node.getListaDefinicaoCorpo() != null)
        {
            node.getListaDefinicaoCorpo().apply(this);
        }
        outAPrograma(node);
    }

    public void inAComGenealogiaOptGenealogia(AComGenealogiaOptGenealogia node)
    {
        defaultIn(node);
    }

    public void outAComGenealogiaOptGenealogia(AComGenealogiaOptGenealogia node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComGenealogiaOptGenealogia(AComGenealogiaOptGenealogia node)
    {
        inAComGenealogiaOptGenealogia(node);
        if(node.getGenealogia() != null)
        {
            node.getGenealogia().apply(this);
        }
        outAComGenealogiaOptGenealogia(node);
    }

    public void inASemGenealogiaOptGenealogia(ASemGenealogiaOptGenealogia node)
    {
        defaultIn(node);
    }

    public void outASemGenealogiaOptGenealogia(ASemGenealogiaOptGenealogia node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASemGenealogiaOptGenealogia(ASemGenealogiaOptGenealogia node)
    {
        inASemGenealogiaOptGenealogia(node);
        outASemGenealogiaOptGenealogia(node);
    }

    public void inAMultiplasListaDefinicaoCorpo(AMultiplasListaDefinicaoCorpo node)
    {
        defaultIn(node);
    }

    public void outAMultiplasListaDefinicaoCorpo(AMultiplasListaDefinicaoCorpo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiplasListaDefinicaoCorpo(AMultiplasListaDefinicaoCorpo node)
    {
        inAMultiplasListaDefinicaoCorpo(node);
        if(node.getListaDefinicaoCorpo() != null)
        {
            node.getListaDefinicaoCorpo().apply(this);
        }
        if(node.getDeclaracaoClasse() != null)
        {
            node.getDeclaracaoClasse().apply(this);
        }
        outAMultiplasListaDefinicaoCorpo(node);
    }

    public void inABaseListaDefinicaoCorpo(ABaseListaDefinicaoCorpo node)
    {
        defaultIn(node);
    }

    public void outABaseListaDefinicaoCorpo(ABaseListaDefinicaoCorpo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABaseListaDefinicaoCorpo(ABaseListaDefinicaoCorpo node)
    {
        inABaseListaDefinicaoCorpo(node);
        if(node.getDeclaracaoClasse() != null)
        {
            node.getDeclaracaoClasse().apply(this);
        }
        outABaseListaDefinicaoCorpo(node);
    }

    public void inAGenealogia(AGenealogia node)
    {
        defaultIn(node);
    }

    public void outAGenealogia(AGenealogia node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGenealogia(AGenealogia node)
    {
        inAGenealogia(node);
        if(node.getRelacao() != null)
        {
            node.getRelacao().apply(this);
        }
        if(node.getListaMaisRelacao() != null)
        {
            node.getListaMaisRelacao().apply(this);
        }
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        outAGenealogia(node);
    }

    public void inAMultiplasListaMaisRelacao(AMultiplasListaMaisRelacao node)
    {
        defaultIn(node);
    }

    public void outAMultiplasListaMaisRelacao(AMultiplasListaMaisRelacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiplasListaMaisRelacao(AMultiplasListaMaisRelacao node)
    {
        inAMultiplasListaMaisRelacao(node);
        if(node.getListaMaisRelacao() != null)
        {
            node.getListaMaisRelacao().apply(this);
        }
        if(node.getMaisRelacao() != null)
        {
            node.getMaisRelacao().apply(this);
        }
        outAMultiplasListaMaisRelacao(node);
    }

    public void inABaseListaMaisRelacao(ABaseListaMaisRelacao node)
    {
        defaultIn(node);
    }

    public void outABaseListaMaisRelacao(ABaseListaMaisRelacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABaseListaMaisRelacao(ABaseListaMaisRelacao node)
    {
        inABaseListaMaisRelacao(node);
        outABaseListaMaisRelacao(node);
    }

    public void inAMaisRelacao(AMaisRelacao node)
    {
        defaultIn(node);
    }

    public void outAMaisRelacao(AMaisRelacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaisRelacao(AMaisRelacao node)
    {
        inAMaisRelacao(node);
        if(node.getEComercial() != null)
        {
            node.getEComercial().apply(this);
        }
        if(node.getRelacao() != null)
        {
            node.getRelacao().apply(this);
        }
        outAMaisRelacao(node);
    }

    public void inARelacao(ARelacao node)
    {
        defaultIn(node);
    }

    public void outARelacao(ARelacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARelacao(ARelacao node)
    {
        inARelacao(node);
        if(node.getFamily() != null)
        {
            node.getFamily().apply(this);
        }
        if(node.getFilho() != null)
        {
            node.getFilho().apply(this);
        }
        if(node.getDerives() != null)
        {
            node.getDerives().apply(this);
        }
        if(node.getFrom() != null)
        {
            node.getFrom().apply(this);
        }
        if(node.getPai() != null)
        {
            node.getPai().apply(this);
        }
        outARelacao(node);
    }

    public void inADeclaracaoClasse(ADeclaracaoClasse node)
    {
        defaultIn(node);
    }

    public void outADeclaracaoClasse(ADeclaracaoClasse node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclaracaoClasse(ADeclaracaoClasse node)
    {
        inADeclaracaoClasse(node);
        if(node.getFamily() != null)
        {
            node.getFamily().apply(this);
        }
        if(node.getIdClasse() != null)
        {
            node.getIdClasse().apply(this);
        }
        if(node.getStart() != null)
        {
            node.getStart().apply(this);
        }
        if(node.getListaComponentes() != null)
        {
            node.getListaComponentes().apply(this);
        }
        if(node.getFinish() != null)
        {
            node.getFinish().apply(this);
        }
        outADeclaracaoClasse(node);
    }

    public void inAMultiplosListaComponentes(AMultiplosListaComponentes node)
    {
        defaultIn(node);
    }

    public void outAMultiplosListaComponentes(AMultiplosListaComponentes node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiplosListaComponentes(AMultiplosListaComponentes node)
    {
        inAMultiplosListaComponentes(node);
        if(node.getListaComponentes() != null)
        {
            node.getListaComponentes().apply(this);
        }
        if(node.getComponentes() != null)
        {
            node.getComponentes().apply(this);
        }
        outAMultiplosListaComponentes(node);
    }

    public void inABaseListaComponentes(ABaseListaComponentes node)
    {
        defaultIn(node);
    }

    public void outABaseListaComponentes(ABaseListaComponentes node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABaseListaComponentes(ABaseListaComponentes node)
    {
        inABaseListaComponentes(node);
        outABaseListaComponentes(node);
    }

    public void inAVarComponentes(AVarComponentes node)
    {
        defaultIn(node);
    }

    public void outAVarComponentes(AVarComponentes node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarComponentes(AVarComponentes node)
    {
        inAVarComponentes(node);
        if(node.getDecVar() != null)
        {
            node.getDecVar().apply(this);
        }
        outAVarComponentes(node);
    }

    public void inAConsComponentes(AConsComponentes node)
    {
        defaultIn(node);
    }

    public void outAConsComponentes(AConsComponentes node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAConsComponentes(AConsComponentes node)
    {
        inAConsComponentes(node);
        if(node.getDecCons() != null)
        {
            node.getDecCons().apply(this);
        }
        outAConsComponentes(node);
    }

    public void inAObjComponentes(AObjComponentes node)
    {
        defaultIn(node);
    }

    public void outAObjComponentes(AObjComponentes node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAObjComponentes(AObjComponentes node)
    {
        inAObjComponentes(node);
        if(node.getDecObj() != null)
        {
            node.getDecObj().apply(this);
        }
        outAObjComponentes(node);
    }

    public void inAMetodoComponentes(AMetodoComponentes node)
    {
        defaultIn(node);
    }

    public void outAMetodoComponentes(AMetodoComponentes node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMetodoComponentes(AMetodoComponentes node)
    {
        inAMetodoComponentes(node);
        if(node.getMetodo() != null)
        {
            node.getMetodo().apply(this);
        }
        outAMetodoComponentes(node);
    }

    public void inADecVar(ADecVar node)
    {
        defaultIn(node);
    }

    public void outADecVar(ADecVar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecVar(ADecVar node)
    {
        inADecVar(node);
        if(node.getAlterable() != null)
        {
            node.getAlterable().apply(this);
        }
        if(node.getTipoPrimitivo() != null)
        {
            node.getTipoPrimitivo().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getAtribuicao() != null)
        {
            node.getAtribuicao().apply(this);
        }
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        outADecVar(node);
    }

    public void inADecCons(ADecCons node)
    {
        defaultIn(node);
    }

    public void outADecCons(ADecCons node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecCons(ADecCons node)
    {
        inADecCons(node);
        if(node.getUnalterable() != null)
        {
            node.getUnalterable().apply(this);
        }
        if(node.getTipoPrimitivo() != null)
        {
            node.getTipoPrimitivo().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getAtribuicao() != null)
        {
            node.getAtribuicao().apply(this);
        }
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        outADecCons(node);
    }

    public void inADecObj(ADecObj node)
    {
        defaultIn(node);
    }

    public void outADecObj(ADecObj node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecObj(ADecObj node)
    {
        inADecObj(node);
        if(node.getObject() != null)
        {
            node.getObject().apply(this);
        }
        if(node.getIdClasse() != null)
        {
            node.getIdClasse().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        outADecObj(node);
    }

    public void inAInteiroTipoPrimitivo(AInteiroTipoPrimitivo node)
    {
        defaultIn(node);
    }

    public void outAInteiroTipoPrimitivo(AInteiroTipoPrimitivo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAInteiroTipoPrimitivo(AInteiroTipoPrimitivo node)
    {
        inAInteiroTipoPrimitivo(node);
        if(node.getNumber() != null)
        {
            node.getNumber().apply(this);
        }
        outAInteiroTipoPrimitivo(node);
    }

    public void inABooleanoTipoPrimitivo(ABooleanoTipoPrimitivo node)
    {
        defaultIn(node);
    }

    public void outABooleanoTipoPrimitivo(ABooleanoTipoPrimitivo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABooleanoTipoPrimitivo(ABooleanoTipoPrimitivo node)
    {
        inABooleanoTipoPrimitivo(node);
        if(node.getAnswer() != null)
        {
            node.getAnswer().apply(this);
        }
        outABooleanoTipoPrimitivo(node);
    }

    public void inAPrimitivoTipo(APrimitivoTipo node)
    {
        defaultIn(node);
    }

    public void outAPrimitivoTipo(APrimitivoTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrimitivoTipo(APrimitivoTipo node)
    {
        inAPrimitivoTipo(node);
        if(node.getTipoPrimitivo() != null)
        {
            node.getTipoPrimitivo().apply(this);
        }
        outAPrimitivoTipo(node);
    }

    public void inAClasseTipo(AClasseTipo node)
    {
        defaultIn(node);
    }

    public void outAClasseTipo(AClasseTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAClasseTipo(AClasseTipo node)
    {
        inAClasseTipo(node);
        if(node.getIdClasse() != null)
        {
            node.getIdClasse().apply(this);
        }
        outAClasseTipo(node);
    }

    public void inAFuncaoConcretaMetodo(AFuncaoConcretaMetodo node)
    {
        defaultIn(node);
    }

    public void outAFuncaoConcretaMetodo(AFuncaoConcretaMetodo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncaoConcretaMetodo(AFuncaoConcretaMetodo node)
    {
        inAFuncaoConcretaMetodo(node);
        if(node.getFunction() != null)
        {
            node.getFunction().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getColcEsq() != null)
        {
            node.getColcEsq().apply(this);
        }
        if(node.getOptParametros() != null)
        {
            node.getOptParametros().apply(this);
        }
        if(node.getColcDir() != null)
        {
            node.getColcDir().apply(this);
        }
        if(node.getBlocoExp() != null)
        {
            node.getBlocoExp().apply(this);
        }
        outAFuncaoConcretaMetodo(node);
    }

    public void inAFuncaoAbstrataMetodo(AFuncaoAbstrataMetodo node)
    {
        defaultIn(node);
    }

    public void outAFuncaoAbstrataMetodo(AFuncaoAbstrataMetodo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFuncaoAbstrataMetodo(AFuncaoAbstrataMetodo node)
    {
        inAFuncaoAbstrataMetodo(node);
        if(node.getFunction() != null)
        {
            node.getFunction().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getColcEsq() != null)
        {
            node.getColcEsq().apply(this);
        }
        if(node.getOptParametros() != null)
        {
            node.getOptParametros().apply(this);
        }
        if(node.getColcDir() != null)
        {
            node.getColcDir().apply(this);
        }
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        outAFuncaoAbstrataMetodo(node);
    }

    public void inAProcedimentoConcrMetodo(AProcedimentoConcrMetodo node)
    {
        defaultIn(node);
    }

    public void outAProcedimentoConcrMetodo(AProcedimentoConcrMetodo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProcedimentoConcrMetodo(AProcedimentoConcrMetodo node)
    {
        inAProcedimentoConcrMetodo(node);
        if(node.getProcedure() != null)
        {
            node.getProcedure().apply(this);
        }
        if(node.getOptMarcadorEntrada() != null)
        {
            node.getOptMarcadorEntrada().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getColcEsq() != null)
        {
            node.getColcEsq().apply(this);
        }
        if(node.getOptParametros() != null)
        {
            node.getOptParametros().apply(this);
        }
        if(node.getColcDir() != null)
        {
            node.getColcDir().apply(this);
        }
        if(node.getBlocoComandos() != null)
        {
            node.getBlocoComandos().apply(this);
        }
        outAProcedimentoConcrMetodo(node);
    }

    public void inAProcedimentoAbstMetodo(AProcedimentoAbstMetodo node)
    {
        defaultIn(node);
    }

    public void outAProcedimentoAbstMetodo(AProcedimentoAbstMetodo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProcedimentoAbstMetodo(AProcedimentoAbstMetodo node)
    {
        inAProcedimentoAbstMetodo(node);
        if(node.getProcedure() != null)
        {
            node.getProcedure().apply(this);
        }
        if(node.getOptMarcadorEntrada() != null)
        {
            node.getOptMarcadorEntrada().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getColcEsq() != null)
        {
            node.getColcEsq().apply(this);
        }
        if(node.getOptParametros() != null)
        {
            node.getOptParametros().apply(this);
        }
        if(node.getColcDir() != null)
        {
            node.getColcDir().apply(this);
        }
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        outAProcedimentoAbstMetodo(node);
    }

    public void inAComMarcadorOptMarcadorEntrada(AComMarcadorOptMarcadorEntrada node)
    {
        defaultIn(node);
    }

    public void outAComMarcadorOptMarcadorEntrada(AComMarcadorOptMarcadorEntrada node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComMarcadorOptMarcadorEntrada(AComMarcadorOptMarcadorEntrada node)
    {
        inAComMarcadorOptMarcadorEntrada(node);
        if(node.getMarcadorEntrada() != null)
        {
            node.getMarcadorEntrada().apply(this);
        }
        outAComMarcadorOptMarcadorEntrada(node);
    }

    public void inASemMarcadorOptMarcadorEntrada(ASemMarcadorOptMarcadorEntrada node)
    {
        defaultIn(node);
    }

    public void outASemMarcadorOptMarcadorEntrada(ASemMarcadorOptMarcadorEntrada node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASemMarcadorOptMarcadorEntrada(ASemMarcadorOptMarcadorEntrada node)
    {
        inASemMarcadorOptMarcadorEntrada(node);
        outASemMarcadorOptMarcadorEntrada(node);
    }

    public void inAComParametrosOptParametros(AComParametrosOptParametros node)
    {
        defaultIn(node);
    }

    public void outAComParametrosOptParametros(AComParametrosOptParametros node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComParametrosOptParametros(AComParametrosOptParametros node)
    {
        inAComParametrosOptParametros(node);
        if(node.getParametros() != null)
        {
            node.getParametros().apply(this);
        }
        outAComParametrosOptParametros(node);
    }

    public void inASemParametrosOptParametros(ASemParametrosOptParametros node)
    {
        defaultIn(node);
    }

    public void outASemParametrosOptParametros(ASemParametrosOptParametros node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASemParametrosOptParametros(ASemParametrosOptParametros node)
    {
        inASemParametrosOptParametros(node);
        outASemParametrosOptParametros(node);
    }

    public void inAParametros(AParametros node)
    {
        defaultIn(node);
    }

    public void outAParametros(AParametros node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParametros(AParametros node)
    {
        inAParametros(node);
        if(node.getParametro() != null)
        {
            node.getParametro().apply(this);
        }
        if(node.getListaMaisParametros() != null)
        {
            node.getListaMaisParametros().apply(this);
        }
        outAParametros(node);
    }

    public void inAMultiplosListaMaisParametros(AMultiplosListaMaisParametros node)
    {
        defaultIn(node);
    }

    public void outAMultiplosListaMaisParametros(AMultiplosListaMaisParametros node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiplosListaMaisParametros(AMultiplosListaMaisParametros node)
    {
        inAMultiplosListaMaisParametros(node);
        if(node.getListaMaisParametros() != null)
        {
            node.getListaMaisParametros().apply(this);
        }
        if(node.getMaisParametros() != null)
        {
            node.getMaisParametros().apply(this);
        }
        outAMultiplosListaMaisParametros(node);
    }

    public void inABaseListaMaisParametros(ABaseListaMaisParametros node)
    {
        defaultIn(node);
    }

    public void outABaseListaMaisParametros(ABaseListaMaisParametros node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABaseListaMaisParametros(ABaseListaMaisParametros node)
    {
        inABaseListaMaisParametros(node);
        outABaseListaMaisParametros(node);
    }

    public void inAMaisParametros(AMaisParametros node)
    {
        defaultIn(node);
    }

    public void outAMaisParametros(AMaisParametros node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaisParametros(AMaisParametros node)
    {
        inAMaisParametros(node);
        if(node.getPipe() != null)
        {
            node.getPipe().apply(this);
        }
        if(node.getParametro() != null)
        {
            node.getParametro().apply(this);
        }
        outAMaisParametros(node);
    }

    public void inAParametro(AParametro node)
    {
        defaultIn(node);
    }

    public void outAParametro(AParametro node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParametro(AParametro node)
    {
        inAParametro(node);
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAParametro(node);
    }

    public void inABlocoComandos(ABlocoComandos node)
    {
        defaultIn(node);
    }

    public void outABlocoComandos(ABlocoComandos node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoComandos(ABlocoComandos node)
    {
        inABlocoComandos(node);
        if(node.getStart() != null)
        {
            node.getStart().apply(this);
        }
        if(node.getListaComando() != null)
        {
            node.getListaComando().apply(this);
        }
        if(node.getFinish() != null)
        {
            node.getFinish().apply(this);
        }
        outABlocoComandos(node);
    }

    public void inABlocoExp(ABlocoExp node)
    {
        defaultIn(node);
    }

    public void outABlocoExp(ABlocoExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoExp(ABlocoExp node)
    {
        inABlocoExp(node);
        if(node.getStart() != null)
        {
            node.getStart().apply(this);
        }
        if(node.getListaDecLocal() != null)
        {
            node.getListaDecLocal().apply(this);
        }
        if(node.getListaComando() != null)
        {
            node.getListaComando().apply(this);
        }
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        if(node.getFinish() != null)
        {
            node.getFinish().apply(this);
        }
        outABlocoExp(node);
    }

    public void inAMultiplosListaDecLocal(AMultiplosListaDecLocal node)
    {
        defaultIn(node);
    }

    public void outAMultiplosListaDecLocal(AMultiplosListaDecLocal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiplosListaDecLocal(AMultiplosListaDecLocal node)
    {
        inAMultiplosListaDecLocal(node);
        if(node.getListaDecLocal() != null)
        {
            node.getListaDecLocal().apply(this);
        }
        if(node.getDecLocal() != null)
        {
            node.getDecLocal().apply(this);
        }
        outAMultiplosListaDecLocal(node);
    }

    public void inABaseListaDecLocal(ABaseListaDecLocal node)
    {
        defaultIn(node);
    }

    public void outABaseListaDecLocal(ABaseListaDecLocal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABaseListaDecLocal(ABaseListaDecLocal node)
    {
        inABaseListaDecLocal(node);
        outABaseListaDecLocal(node);
    }

    public void inAVarDecLocal(AVarDecLocal node)
    {
        defaultIn(node);
    }

    public void outAVarDecLocal(AVarDecLocal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarDecLocal(AVarDecLocal node)
    {
        inAVarDecLocal(node);
        if(node.getDecVar() != null)
        {
            node.getDecVar().apply(this);
        }
        outAVarDecLocal(node);
    }

    public void inAConsDecLocal(AConsDecLocal node)
    {
        defaultIn(node);
    }

    public void outAConsDecLocal(AConsDecLocal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAConsDecLocal(AConsDecLocal node)
    {
        inAConsDecLocal(node);
        if(node.getDecCons() != null)
        {
            node.getDecCons().apply(this);
        }
        outAConsDecLocal(node);
    }

    public void inAObjDecLocal(AObjDecLocal node)
    {
        defaultIn(node);
    }

    public void outAObjDecLocal(AObjDecLocal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAObjDecLocal(AObjDecLocal node)
    {
        inAObjDecLocal(node);
        if(node.getDecObj() != null)
        {
            node.getDecObj().apply(this);
        }
        outAObjDecLocal(node);
    }

    public void inAMultiplosListaComando(AMultiplosListaComando node)
    {
        defaultIn(node);
    }

    public void outAMultiplosListaComando(AMultiplosListaComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiplosListaComando(AMultiplosListaComando node)
    {
        inAMultiplosListaComando(node);
        if(node.getListaComando() != null)
        {
            node.getListaComando().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        outAMultiplosListaComando(node);
    }

    public void inABaseListaComando(ABaseListaComando node)
    {
        defaultIn(node);
    }

    public void outABaseListaComando(ABaseListaComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABaseListaComando(ABaseListaComando node)
    {
        inABaseListaComando(node);
        outABaseListaComando(node);
    }

    public void inAAtribuicaoComando(AAtribuicaoComando node)
    {
        defaultIn(node);
    }

    public void outAAtribuicaoComando(AAtribuicaoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtribuicaoComando(AAtribuicaoComando node)
    {
        inAAtribuicaoComando(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getAtribuicao() != null)
        {
            node.getAtribuicao().apply(this);
        }
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        outAAtribuicaoComando(node);
    }

    public void inAChamadaCmdComando(AChamadaCmdComando node)
    {
        defaultIn(node);
    }

    public void outAChamadaCmdComando(AChamadaCmdComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAChamadaCmdComando(AChamadaCmdComando node)
    {
        inAChamadaCmdComando(node);
        if(node.getOptListaPrefixoAcesso() != null)
        {
            node.getOptListaPrefixoAcesso().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getColcEsq() != null)
        {
            node.getColcEsq().apply(this);
        }
        if(node.getOptListaExp() != null)
        {
            node.getOptListaExp().apply(this);
        }
        if(node.getColcDir() != null)
        {
            node.getColcDir().apply(this);
        }
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        outAChamadaCmdComando(node);
    }

    public void inACondicionalComando(ACondicionalComando node)
    {
        defaultIn(node);
    }

    public void outACondicionalComando(ACondicionalComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACondicionalComando(ACondicionalComando node)
    {
        inACondicionalComando(node);
        if(node.getIn() != null)
        {
            node.getIn().apply(this);
        }
        if(node.getCase() != null)
        {
            node.getCase().apply(this);
        }
        if(node.getThat() != null)
        {
            node.getThat().apply(this);
        }
        if(node.getParEsq() != null)
        {
            node.getParEsq().apply(this);
        }
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        if(node.getParDir() != null)
        {
            node.getParDir().apply(this);
        }
        if(node.getBlocoComandos() != null)
        {
            node.getBlocoComandos().apply(this);
        }
        if(node.getOptCmdOtherwise() != null)
        {
            node.getOptCmdOtherwise().apply(this);
        }
        outACondicionalComando(node);
    }

    public void inALacoComando(ALacoComando node)
    {
        defaultIn(node);
    }

    public void outALacoComando(ALacoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALacoComando(ALacoComando node)
    {
        inALacoComando(node);
        if(node.getAbreAs() != null)
        {
            node.getAbreAs().apply(this);
        }
        if(node.getLong() != null)
        {
            node.getLong().apply(this);
        }
        if(node.getFechaAs() != null)
        {
            node.getFechaAs().apply(this);
        }
        if(node.getParEsq() != null)
        {
            node.getParEsq().apply(this);
        }
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        if(node.getParDir() != null)
        {
            node.getParDir().apply(this);
        }
        if(node.getBlocoComandos() != null)
        {
            node.getBlocoComandos().apply(this);
        }
        outALacoComando(node);
    }

    public void inABlocoComando(ABlocoComando node)
    {
        defaultIn(node);
    }

    public void outABlocoComando(ABlocoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoComando(ABlocoComando node)
    {
        inABlocoComando(node);
        if(node.getBlocoComandos() != null)
        {
            node.getBlocoComandos().apply(this);
        }
        outABlocoComando(node);
    }

    public void inAComOtherwiseOptCmdOtherwise(AComOtherwiseOptCmdOtherwise node)
    {
        defaultIn(node);
    }

    public void outAComOtherwiseOptCmdOtherwise(AComOtherwiseOptCmdOtherwise node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComOtherwiseOptCmdOtherwise(AComOtherwiseOptCmdOtherwise node)
    {
        inAComOtherwiseOptCmdOtherwise(node);
        if(node.getOtherwise() != null)
        {
            node.getOtherwise().apply(this);
        }
        if(node.getBlocoComandos() != null)
        {
            node.getBlocoComandos().apply(this);
        }
        outAComOtherwiseOptCmdOtherwise(node);
    }

    public void inASemOtherwiseOptCmdOtherwise(ASemOtherwiseOptCmdOtherwise node)
    {
        defaultIn(node);
    }

    public void outASemOtherwiseOptCmdOtherwise(ASemOtherwiseOptCmdOtherwise node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASemOtherwiseOptCmdOtherwise(ASemOtherwiseOptCmdOtherwise node)
    {
        inASemOtherwiseOptCmdOtherwise(node);
        outASemOtherwiseOptCmdOtherwise(node);
    }

    public void inAComExpressaoOptExpressao(AComExpressaoOptExpressao node)
    {
        defaultIn(node);
    }

    public void outAComExpressaoOptExpressao(AComExpressaoOptExpressao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComExpressaoOptExpressao(AComExpressaoOptExpressao node)
    {
        inAComExpressaoOptExpressao(node);
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        outAComExpressaoOptExpressao(node);
    }

    public void inASemExpressaoOptExpressao(ASemExpressaoOptExpressao node)
    {
        defaultIn(node);
    }

    public void outASemExpressaoOptExpressao(ASemExpressaoOptExpressao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASemExpressaoOptExpressao(ASemExpressaoOptExpressao node)
    {
        inASemExpressaoOptExpressao(node);
        outASemExpressaoOptExpressao(node);
    }

    public void inATernarioExprExpressao(ATernarioExprExpressao node)
    {
        defaultIn(node);
    }

    public void outATernarioExprExpressao(ATernarioExprExpressao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATernarioExprExpressao(ATernarioExprExpressao node)
    {
        inATernarioExprExpressao(node);
        if(node.getIf() != null)
        {
            node.getIf().apply(this);
        }
        if(node.getParEsq() != null)
        {
            node.getParEsq().apply(this);
        }
        if(node.getCond() != null)
        {
            node.getCond().apply(this);
        }
        if(node.getParDir() != null)
        {
            node.getParDir().apply(this);
        }
        if(node.getVTrue() != null)
        {
            node.getVTrue().apply(this);
        }
        if(node.getElse() != null)
        {
            node.getElse().apply(this);
        }
        if(node.getVFalse() != null)
        {
            node.getVFalse().apply(this);
        }
        outATernarioExprExpressao(node);
    }

    public void inASimplesExpressao(ASimplesExpressao node)
    {
        defaultIn(node);
    }

    public void outASimplesExpressao(ASimplesExpressao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASimplesExpressao(ASimplesExpressao node)
    {
        inASimplesExpressao(node);
        if(node.getExpressaoOu() != null)
        {
            node.getExpressaoOu().apply(this);
        }
        outASimplesExpressao(node);
    }

    public void inAOuExpressaoOu(AOuExpressaoOu node)
    {
        defaultIn(node);
    }

    public void outAOuExpressaoOu(AOuExpressaoOu node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOuExpressaoOu(AOuExpressaoOu node)
    {
        inAOuExpressaoOu(node);
        if(node.getExpressaoOu() != null)
        {
            node.getExpressaoOu().apply(this);
        }
        if(node.getOr() != null)
        {
            node.getOr().apply(this);
        }
        if(node.getExpressaoAnd() != null)
        {
            node.getExpressaoAnd().apply(this);
        }
        outAOuExpressaoOu(node);
    }

    public void inASimplesExpressaoOu(ASimplesExpressaoOu node)
    {
        defaultIn(node);
    }

    public void outASimplesExpressaoOu(ASimplesExpressaoOu node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASimplesExpressaoOu(ASimplesExpressaoOu node)
    {
        inASimplesExpressaoOu(node);
        if(node.getExpressaoAnd() != null)
        {
            node.getExpressaoAnd().apply(this);
        }
        outASimplesExpressaoOu(node);
    }

    public void inAEExpressaoAnd(AEExpressaoAnd node)
    {
        defaultIn(node);
    }

    public void outAEExpressaoAnd(AEExpressaoAnd node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEExpressaoAnd(AEExpressaoAnd node)
    {
        inAEExpressaoAnd(node);
        if(node.getExpressaoAnd() != null)
        {
            node.getExpressaoAnd().apply(this);
        }
        if(node.getAnd() != null)
        {
            node.getAnd().apply(this);
        }
        if(node.getExpressaoRelacional() != null)
        {
            node.getExpressaoRelacional().apply(this);
        }
        outAEExpressaoAnd(node);
    }

    public void inASimplesExpressaoAnd(ASimplesExpressaoAnd node)
    {
        defaultIn(node);
    }

    public void outASimplesExpressaoAnd(ASimplesExpressaoAnd node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASimplesExpressaoAnd(ASimplesExpressaoAnd node)
    {
        inASimplesExpressaoAnd(node);
        if(node.getExpressaoRelacional() != null)
        {
            node.getExpressaoRelacional().apply(this);
        }
        outASimplesExpressaoAnd(node);
    }

    public void inAMenorExpressaoRelacional(AMenorExpressaoRelacional node)
    {
        defaultIn(node);
    }

    public void outAMenorExpressaoRelacional(AMenorExpressaoRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenorExpressaoRelacional(AMenorExpressaoRelacional node)
    {
        inAMenorExpressaoRelacional(node);
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        if(node.getMenor() != null)
        {
            node.getMenor().apply(this);
        }
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        outAMenorExpressaoRelacional(node);
    }

    public void inAMaiorExpressaoRelacional(AMaiorExpressaoRelacional node)
    {
        defaultIn(node);
    }

    public void outAMaiorExpressaoRelacional(AMaiorExpressaoRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaiorExpressaoRelacional(AMaiorExpressaoRelacional node)
    {
        inAMaiorExpressaoRelacional(node);
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        if(node.getMaior() != null)
        {
            node.getMaior().apply(this);
        }
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        outAMaiorExpressaoRelacional(node);
    }

    public void inAIgualExpressaoRelacional(AIgualExpressaoRelacional node)
    {
        defaultIn(node);
    }

    public void outAIgualExpressaoRelacional(AIgualExpressaoRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIgualExpressaoRelacional(AIgualExpressaoRelacional node)
    {
        inAIgualExpressaoRelacional(node);
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        if(node.getIgual() != null)
        {
            node.getIgual().apply(this);
        }
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        outAIgualExpressaoRelacional(node);
    }

    public void inASimplesExpressaoRelacional(ASimplesExpressaoRelacional node)
    {
        defaultIn(node);
    }

    public void outASimplesExpressaoRelacional(ASimplesExpressaoRelacional node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASimplesExpressaoRelacional(ASimplesExpressaoRelacional node)
    {
        inASimplesExpressaoRelacional(node);
        if(node.getExpressaoAritmetica() != null)
        {
            node.getExpressaoAritmetica().apply(this);
        }
        outASimplesExpressaoRelacional(node);
    }

    public void inASomaExpressaoAritmetica(ASomaExpressaoAritmetica node)
    {
        defaultIn(node);
    }

    public void outASomaExpressaoAritmetica(ASomaExpressaoAritmetica node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASomaExpressaoAritmetica(ASomaExpressaoAritmetica node)
    {
        inASomaExpressaoAritmetica(node);
        if(node.getExpressaoAritmetica() != null)
        {
            node.getExpressaoAritmetica().apply(this);
        }
        if(node.getSoma() != null)
        {
            node.getSoma().apply(this);
        }
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        outASomaExpressaoAritmetica(node);
    }

    public void inASubtracaoExpressaoAritmetica(ASubtracaoExpressaoAritmetica node)
    {
        defaultIn(node);
    }

    public void outASubtracaoExpressaoAritmetica(ASubtracaoExpressaoAritmetica node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASubtracaoExpressaoAritmetica(ASubtracaoExpressaoAritmetica node)
    {
        inASubtracaoExpressaoAritmetica(node);
        if(node.getExpressaoAritmetica() != null)
        {
            node.getExpressaoAritmetica().apply(this);
        }
        if(node.getMenos() != null)
        {
            node.getMenos().apply(this);
        }
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        outASubtracaoExpressaoAritmetica(node);
    }

    public void inASimplesExpressaoAritmetica(ASimplesExpressaoAritmetica node)
    {
        defaultIn(node);
    }

    public void outASimplesExpressaoAritmetica(ASimplesExpressaoAritmetica node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASimplesExpressaoAritmetica(ASimplesExpressaoAritmetica node)
    {
        inASimplesExpressaoAritmetica(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        outASimplesExpressaoAritmetica(node);
    }

    public void inAMultiplicacaoTermo(AMultiplicacaoTermo node)
    {
        defaultIn(node);
    }

    public void outAMultiplicacaoTermo(AMultiplicacaoTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiplicacaoTermo(AMultiplicacaoTermo node)
    {
        inAMultiplicacaoTermo(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        if(node.getMult() != null)
        {
            node.getMult().apply(this);
        }
        if(node.getFator() != null)
        {
            node.getFator().apply(this);
        }
        outAMultiplicacaoTermo(node);
    }

    public void inADivisaoTermo(ADivisaoTermo node)
    {
        defaultIn(node);
    }

    public void outADivisaoTermo(ADivisaoTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivisaoTermo(ADivisaoTermo node)
    {
        inADivisaoTermo(node);
        if(node.getTermo() != null)
        {
            node.getTermo().apply(this);
        }
        if(node.getDiv() != null)
        {
            node.getDiv().apply(this);
        }
        if(node.getFator() != null)
        {
            node.getFator().apply(this);
        }
        outADivisaoTermo(node);
    }

    public void inASimplesTermo(ASimplesTermo node)
    {
        defaultIn(node);
    }

    public void outASimplesTermo(ASimplesTermo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASimplesTermo(ASimplesTermo node)
    {
        inASimplesTermo(node);
        if(node.getFator() != null)
        {
            node.getFator().apply(this);
        }
        outASimplesTermo(node);
    }

    public void inAIdFator(AIdFator node)
    {
        defaultIn(node);
    }

    public void outAIdFator(AIdFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdFator(AIdFator node)
    {
        inAIdFator(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAIdFator(node);
    }

    public void inAInteiroFator(AInteiroFator node)
    {
        defaultIn(node);
    }

    public void outAInteiroFator(AInteiroFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAInteiroFator(AInteiroFator node)
    {
        inAInteiroFator(node);
        if(node.getValorInteiro() != null)
        {
            node.getValorInteiro().apply(this);
        }
        outAInteiroFator(node);
    }

    public void inARealFator(ARealFator node)
    {
        defaultIn(node);
    }

    public void outARealFator(ARealFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARealFator(ARealFator node)
    {
        inARealFator(node);
        if(node.getValorReal() != null)
        {
            node.getValorReal().apply(this);
        }
        outARealFator(node);
    }

    public void inABooleanoVFator(ABooleanoVFator node)
    {
        defaultIn(node);
    }

    public void outABooleanoVFator(ABooleanoVFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABooleanoVFator(ABooleanoVFator node)
    {
        inABooleanoVFator(node);
        if(node.getYes() != null)
        {
            node.getYes().apply(this);
        }
        outABooleanoVFator(node);
    }

    public void inABooleanoFFator(ABooleanoFFator node)
    {
        defaultIn(node);
    }

    public void outABooleanoFFator(ABooleanoFFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABooleanoFFator(ABooleanoFFator node)
    {
        inABooleanoFFator(node);
        if(node.getNo() != null)
        {
            node.getNo().apply(this);
        }
        outABooleanoFFator(node);
    }

    public void inANegacaoFator(ANegacaoFator node)
    {
        defaultIn(node);
    }

    public void outANegacaoFator(ANegacaoFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANegacaoFator(ANegacaoFator node)
    {
        inANegacaoFator(node);
        if(node.getNao() != null)
        {
            node.getNao().apply(this);
        }
        if(node.getFator() != null)
        {
            node.getFator().apply(this);
        }
        outANegacaoFator(node);
    }

    public void inAMenosUnarioFator(AMenosUnarioFator node)
    {
        defaultIn(node);
    }

    public void outAMenosUnarioFator(AMenosUnarioFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenosUnarioFator(AMenosUnarioFator node)
    {
        inAMenosUnarioFator(node);
        if(node.getMenos() != null)
        {
            node.getMenos().apply(this);
        }
        if(node.getFator() != null)
        {
            node.getFator().apply(this);
        }
        outAMenosUnarioFator(node);
    }

    public void inAAcessoSetaFator(AAcessoSetaFator node)
    {
        defaultIn(node);
    }

    public void outAAcessoSetaFator(AAcessoSetaFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAcessoSetaFator(AAcessoSetaFator node)
    {
        inAAcessoSetaFator(node);
        if(node.getListaPrefixoAcesso() != null)
        {
            node.getListaPrefixoAcesso().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAAcessoSetaFator(node);
    }

    public void inAChamadaExprFator(AChamadaExprFator node)
    {
        defaultIn(node);
    }

    public void outAChamadaExprFator(AChamadaExprFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAChamadaExprFator(AChamadaExprFator node)
    {
        inAChamadaExprFator(node);
        if(node.getOptListaPrefixoAcesso() != null)
        {
            node.getOptListaPrefixoAcesso().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getColcEsq() != null)
        {
            node.getColcEsq().apply(this);
        }
        if(node.getOptListaExp() != null)
        {
            node.getOptListaExp().apply(this);
        }
        if(node.getColcDir() != null)
        {
            node.getColcDir().apply(this);
        }
        outAChamadaExprFator(node);
    }

    public void inAParentesesFator(AParentesesFator node)
    {
        defaultIn(node);
    }

    public void outAParentesesFator(AParentesesFator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParentesesFator(AParentesesFator node)
    {
        inAParentesesFator(node);
        if(node.getParEsq() != null)
        {
            node.getParEsq().apply(this);
        }
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        if(node.getParDir() != null)
        {
            node.getParDir().apply(this);
        }
        outAParentesesFator(node);
    }

    public void inAMultiplosListaPrefixoAcesso(AMultiplosListaPrefixoAcesso node)
    {
        defaultIn(node);
    }

    public void outAMultiplosListaPrefixoAcesso(AMultiplosListaPrefixoAcesso node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiplosListaPrefixoAcesso(AMultiplosListaPrefixoAcesso node)
    {
        inAMultiplosListaPrefixoAcesso(node);
        if(node.getListaPrefixoAcesso() != null)
        {
            node.getListaPrefixoAcesso().apply(this);
        }
        if(node.getPrefixoAcesso() != null)
        {
            node.getPrefixoAcesso().apply(this);
        }
        outAMultiplosListaPrefixoAcesso(node);
    }

    public void inABaseListaPrefixoAcesso(ABaseListaPrefixoAcesso node)
    {
        defaultIn(node);
    }

    public void outABaseListaPrefixoAcesso(ABaseListaPrefixoAcesso node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABaseListaPrefixoAcesso(ABaseListaPrefixoAcesso node)
    {
        inABaseListaPrefixoAcesso(node);
        if(node.getPrefixoAcesso() != null)
        {
            node.getPrefixoAcesso().apply(this);
        }
        outABaseListaPrefixoAcesso(node);
    }

    public void inAComAcessoOptListaPrefixoAcesso(AComAcessoOptListaPrefixoAcesso node)
    {
        defaultIn(node);
    }

    public void outAComAcessoOptListaPrefixoAcesso(AComAcessoOptListaPrefixoAcesso node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComAcessoOptListaPrefixoAcesso(AComAcessoOptListaPrefixoAcesso node)
    {
        inAComAcessoOptListaPrefixoAcesso(node);
        if(node.getListaPrefixoAcesso() != null)
        {
            node.getListaPrefixoAcesso().apply(this);
        }
        outAComAcessoOptListaPrefixoAcesso(node);
    }

    public void inASemAcessoOptListaPrefixoAcesso(ASemAcessoOptListaPrefixoAcesso node)
    {
        defaultIn(node);
    }

    public void outASemAcessoOptListaPrefixoAcesso(ASemAcessoOptListaPrefixoAcesso node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASemAcessoOptListaPrefixoAcesso(ASemAcessoOptListaPrefixoAcesso node)
    {
        inASemAcessoOptListaPrefixoAcesso(node);
        outASemAcessoOptListaPrefixoAcesso(node);
    }

    public void inAPrefixoAcesso(APrefixoAcesso node)
    {
        defaultIn(node);
    }

    public void outAPrefixoAcesso(APrefixoAcesso node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPrefixoAcesso(APrefixoAcesso node)
    {
        inAPrefixoAcesso(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getSeta() != null)
        {
            node.getSeta().apply(this);
        }
        outAPrefixoAcesso(node);
    }

    public void inAComExpOptListaExp(AComExpOptListaExp node)
    {
        defaultIn(node);
    }

    public void outAComExpOptListaExp(AComExpOptListaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComExpOptListaExp(AComExpOptListaExp node)
    {
        inAComExpOptListaExp(node);
        if(node.getListaExp() != null)
        {
            node.getListaExp().apply(this);
        }
        outAComExpOptListaExp(node);
    }

    public void inASemExpOptListaExp(ASemExpOptListaExp node)
    {
        defaultIn(node);
    }

    public void outASemExpOptListaExp(ASemExpOptListaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASemExpOptListaExp(ASemExpOptListaExp node)
    {
        inASemExpOptListaExp(node);
        outASemExpOptListaExp(node);
    }

    public void inAListaExp(AListaExp node)
    {
        defaultIn(node);
    }

    public void outAListaExp(AListaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaExp(AListaExp node)
    {
        inAListaExp(node);
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        if(node.getListaMaisExp() != null)
        {
            node.getListaMaisExp().apply(this);
        }
        outAListaExp(node);
    }

    public void inAMultiplosListaMaisExp(AMultiplosListaMaisExp node)
    {
        defaultIn(node);
    }

    public void outAMultiplosListaMaisExp(AMultiplosListaMaisExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiplosListaMaisExp(AMultiplosListaMaisExp node)
    {
        inAMultiplosListaMaisExp(node);
        if(node.getListaMaisExp() != null)
        {
            node.getListaMaisExp().apply(this);
        }
        if(node.getMaisExp() != null)
        {
            node.getMaisExp().apply(this);
        }
        outAMultiplosListaMaisExp(node);
    }

    public void inABaseListaMaisExp(ABaseListaMaisExp node)
    {
        defaultIn(node);
    }

    public void outABaseListaMaisExp(ABaseListaMaisExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABaseListaMaisExp(ABaseListaMaisExp node)
    {
        inABaseListaMaisExp(node);
        outABaseListaMaisExp(node);
    }

    public void inAMaisExp(AMaisExp node)
    {
        defaultIn(node);
    }

    public void outAMaisExp(AMaisExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaisExp(AMaisExp node)
    {
        inAMaisExp(node);
        if(node.getPipe() != null)
        {
            node.getPipe().apply(this);
        }
        if(node.getExpressao() != null)
        {
            node.getExpressao().apply(this);
        }
        outAMaisExp(node);
    }
}
