/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.analysis;

import java.util.*;
import dplusplus.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPGenealogia().apply(this);
        outStart(node);
    }

    public void inAGenealogia(AGenealogia node)
    {
        defaultIn(node);
    }

    public void outAGenealogia(AGenealogia node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGenealogia(AGenealogia node)
    {
        inAGenealogia(node);
        if(node.getPonto() != null)
        {
            node.getPonto().apply(this);
        }
        {
            List<PMaisRelacao> copy = new ArrayList<PMaisRelacao>(node.getMaisRelacao());
            Collections.reverse(copy);
            for(PMaisRelacao e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRelacao() != null)
        {
            node.getRelacao().apply(this);
        }
        outAGenealogia(node);
    }

    public void inAMaisRelacao(AMaisRelacao node)
    {
        defaultIn(node);
    }

    public void outAMaisRelacao(AMaisRelacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaisRelacao(AMaisRelacao node)
    {
        inAMaisRelacao(node);
        if(node.getRelacao() != null)
        {
            node.getRelacao().apply(this);
        }
        if(node.getEComercial() != null)
        {
            node.getEComercial().apply(this);
        }
        outAMaisRelacao(node);
    }

    public void inARelacao(ARelacao node)
    {
        defaultIn(node);
    }

    public void outARelacao(ARelacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARelacao(ARelacao node)
    {
        inARelacao(node);
        if(node.getPai() != null)
        {
            node.getPai().apply(this);
        }
        if(node.getFrom() != null)
        {
            node.getFrom().apply(this);
        }
        if(node.getDerives() != null)
        {
            node.getDerives().apply(this);
        }
        if(node.getFilho() != null)
        {
            node.getFilho().apply(this);
        }
        if(node.getFamily() != null)
        {
            node.getFamily().apply(this);
        }
        outARelacao(node);
    }

    public void inATipoClasse(ATipoClasse node)
    {
        defaultIn(node);
    }

    public void outATipoClasse(ATipoClasse node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATipoClasse(ATipoClasse node)
    {
        inATipoClasse(node);
        if(node.getIdClasse() != null)
        {
            node.getIdClasse().apply(this);
        }
        outATipoClasse(node);
    }
}
