/* This file was generated by SableCC (http://www.sablecc.org/). */

package dplusplus.parser;

import dplusplus.node.*;
import dplusplus.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTValorReal(@SuppressWarnings("unused") TValorReal node)
    {
        this.index = 0;
    }

    @Override
    public void caseTValorInteiro(@SuppressWarnings("unused") TValorInteiro node)
    {
        this.index = 1;
    }

    @Override
    public void caseTYes(@SuppressWarnings("unused") TYes node)
    {
        this.index = 2;
    }

    @Override
    public void caseTNo(@SuppressWarnings("unused") TNo node)
    {
        this.index = 3;
    }

    @Override
    public void caseTSoma(@SuppressWarnings("unused") TSoma node)
    {
        this.index = 4;
    }

    @Override
    public void caseTMenos(@SuppressWarnings("unused") TMenos node)
    {
        this.index = 5;
    }

    @Override
    public void caseTMult(@SuppressWarnings("unused") TMult node)
    {
        this.index = 6;
    }

    @Override
    public void caseTDiv(@SuppressWarnings("unused") TDiv node)
    {
        this.index = 7;
    }

    @Override
    public void caseTIgual(@SuppressWarnings("unused") TIgual node)
    {
        this.index = 8;
    }

    @Override
    public void caseTMenor(@SuppressWarnings("unused") TMenor node)
    {
        this.index = 9;
    }

    @Override
    public void caseTMaior(@SuppressWarnings("unused") TMaior node)
    {
        this.index = 10;
    }

    @Override
    public void caseTNao(@SuppressWarnings("unused") TNao node)
    {
        this.index = 11;
    }

    @Override
    public void caseTAnd(@SuppressWarnings("unused") TAnd node)
    {
        this.index = 12;
    }

    @Override
    public void caseTOr(@SuppressWarnings("unused") TOr node)
    {
        this.index = 13;
    }

    @Override
    public void caseTSeta(@SuppressWarnings("unused") TSeta node)
    {
        this.index = 14;
    }

    @Override
    public void caseTAtribuicao(@SuppressWarnings("unused") TAtribuicao node)
    {
        this.index = 15;
    }

    @Override
    public void caseTPonto(@SuppressWarnings("unused") TPonto node)
    {
        this.index = 16;
    }

    @Override
    public void caseTEComercial(@SuppressWarnings("unused") TEComercial node)
    {
        this.index = 17;
    }

    @Override
    public void caseTPipe(@SuppressWarnings("unused") TPipe node)
    {
        this.index = 18;
    }

    @Override
    public void caseTParEsq(@SuppressWarnings("unused") TParEsq node)
    {
        this.index = 19;
    }

    @Override
    public void caseTParDir(@SuppressWarnings("unused") TParDir node)
    {
        this.index = 20;
    }

    @Override
    public void caseTColcEsq(@SuppressWarnings("unused") TColcEsq node)
    {
        this.index = 21;
    }

    @Override
    public void caseTColcDir(@SuppressWarnings("unused") TColcDir node)
    {
        this.index = 22;
    }

    @Override
    public void caseTFinish(@SuppressWarnings("unused") TFinish node)
    {
        this.index = 23;
    }

    @Override
    public void caseTStart(@SuppressWarnings("unused") TStart node)
    {
        this.index = 24;
    }

    @Override
    public void caseTIn(@SuppressWarnings("unused") TIn node)
    {
        this.index = 25;
    }

    @Override
    public void caseTCase(@SuppressWarnings("unused") TCase node)
    {
        this.index = 26;
    }

    @Override
    public void caseTThat(@SuppressWarnings("unused") TThat node)
    {
        this.index = 27;
    }

    @Override
    public void caseTAsLongAs(@SuppressWarnings("unused") TAsLongAs node)
    {
        this.index = 28;
    }

    @Override
    public void caseTOtherwise(@SuppressWarnings("unused") TOtherwise node)
    {
        this.index = 29;
    }

    @Override
    public void caseTIf(@SuppressWarnings("unused") TIf node)
    {
        this.index = 30;
    }

    @Override
    public void caseTElse(@SuppressWarnings("unused") TElse node)
    {
        this.index = 31;
    }

    @Override
    public void caseTFamily(@SuppressWarnings("unused") TFamily node)
    {
        this.index = 32;
    }

    @Override
    public void caseTDerives(@SuppressWarnings("unused") TDerives node)
    {
        this.index = 33;
    }

    @Override
    public void caseTFrom(@SuppressWarnings("unused") TFrom node)
    {
        this.index = 34;
    }

    @Override
    public void caseTObject(@SuppressWarnings("unused") TObject node)
    {
        this.index = 35;
    }

    @Override
    public void caseTFunction(@SuppressWarnings("unused") TFunction node)
    {
        this.index = 36;
    }

    @Override
    public void caseTProcedure(@SuppressWarnings("unused") TProcedure node)
    {
        this.index = 37;
    }

    @Override
    public void caseTAlterable(@SuppressWarnings("unused") TAlterable node)
    {
        this.index = 38;
    }

    @Override
    public void caseTUnalterable(@SuppressWarnings("unused") TUnalterable node)
    {
        this.index = 39;
    }

    @Override
    public void caseTAnswer(@SuppressWarnings("unused") TAnswer node)
    {
        this.index = 40;
    }

    @Override
    public void caseTNumber(@SuppressWarnings("unused") TNumber node)
    {
        this.index = 41;
    }

    @Override
    public void caseTMarcadorEntrada(@SuppressWarnings("unused") TMarcadorEntrada node)
    {
        this.index = 42;
    }

    @Override
    public void caseTIdClasse(@SuppressWarnings("unused") TIdClasse node)
    {
        this.index = 43;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 44;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 45;
    }
}
