/* This file was generated by SableCC (http://www.sablecc.org/). */

package lexico.analysis;

import lexico.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTNumero(TNumero node);
    void caseTYes(TYes node);
    void caseTNo(TNo node);
    void caseTSoma(TSoma node);
    void caseTMenos(TMenos node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTMod(TMod node);
    void caseTMenor(TMenor node);
    void caseTMaior(TMaior node);
    void caseTAtribuicao(TAtribuicao node);
    void caseTPonto(TPonto node);
    void caseTParEsq(TParEsq node);
    void caseTParDir(TParDir node);
    void caseTColcEsq(TColcEsq node);
    void caseTColcDir(TColcDir node);
    void caseTStart(TStart node);
    void caseTFamily(TFamily node);
    void caseTMarcadorEntrada(TMarcadorEntrada node);
    void caseTIdClasse(TIdClasse node);
    void caseTId(TId node);
    void caseTVazio(TVazio node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
